# -*- coding: utf-8 -*-
"""Week5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17OOZK_aRnHqEOFs4-ez8rJwCilxT1Bd2

# Control Flow & Functions

## Why this matters?

Most real programs are: decisions + repetition + reusable building blocks.

This file focuses on:
- Decisions: `if/elif/else`, `match/case` (and *why* `match/case` can be clearer than long `if/elif` chains)
- Repetition: `for/while`, `break/continue`, `enumerate`, `zip` (tuple-unpacking)
- Reuse: functions (parameters, defaults, docstrings, type hints, multiple returns)

## Notes for learners

- `elif` must immediately follow the `if` it belongs to (only comments/blank lines may be in between).
- Truthiness: `0`, `0.0`, `''`, `[]`, `{}` are `False`; non-zero numbers and non-empty containers are `True`. Try: `print(bool(0), bool(2))` to see it.
- Prefer clarity over cleverness. We'll show both clear and compact patterns when helpful.
- Safety: For `while True` loops, we include a small safeguard counter to avoid accidental infinite loops.
- Python 3.10+ is assumed for `str | None` type hints and `match/case`. On 3.9 use `Optional[str]` and `if/elif`.

### if/elif/else

Syntax:

```
if (condition1):
  do action1         # executed if 'condition1' == True
elif (condition2):
  do action2
...
else:
  do action{N}       # action{N} with condition1, condition2, ..., condition{N-1} all being False
```
"""

test_input = 'Jin'

# `isinstance()` is a function that checks if an input is equal to a type of
# interest (ex. `isinstance([1, 2, 3], list)`       -> True)
#          (    `isinstance({'A': 1, 'B': 2}, dict) -> True)
if isinstance(test_input, str):
  # `isinstance(test_string, str)` is True, so below will run.
  # Again, we see the use of F string here.
  print(f"Input is a string: {test_input}")

# You can have as many `elif`s as you need/want
elif isinstance(test_input, int):
  print(f"Input is an integer: {test_input}")
elif isinstance(test_input, list):
  print(f"Input is a list: {test_input}")
# Below is not necessary when you don't want to do anything with False
# condition.
else:
  print("Eh, input is not a string")

"""### if/else in list comprehension

- Binary choice (only consider True cases): \
`[(action) for x in {iterable} if (condition)]`
- Additional treatment specified: \
`[(action1) if (condition) else (action2) for x in {iterable}`]
"""

# Only consider True (i.e. non-zero numbers) cases
integers = range(10)
# Odd numbers or even numbers?
odd_or_even = [x for x in integers if x % 2]

"""`%` is a modulo operator in Python (ex. `3 % 2 = 1`).

1. {iterable} is `range(10)`. This means `x` will be 0, 1, 2, ... 9 at each iteration
2. (action) is `x`, which means to *append* `x` to a list.
3. (condition) is `x % 2`. At each iteration, if this is `True`, append `x`.

In **boolean indexing**, 0 is `False`, and any non-zero number is `True` (yes, not only 1, but 2, 3, etc.).

- If `x` is *even*, then `x % 2 == 0 (False)` -> `x` not appended to the list.
- If `x` is *odd*, then `x % 2 == 1 (True)` -> `x` appended to the list.
"""

odd_or_even

"""You can include `else` in a (list) comprehension."""

# `else` in a list comprehension
odd_or_even2 = ['Odd' if y % 2 else 'Even' for y in integers]
odd_or_even2

"""`elif` is not directly used in a list comprehension. Instead, you 'nest' an `if-else` condition inside an `else` condition.

- Typical `if/elif/else` statement:
  ```
  a_list = list()
  for x in {iterable}:
    if (condition1):
      a_list.append(action1)
    elif (condition2):
      a_list.append(action2)
    else:
      a_list.append(action3)
  ```
- List comprehension's case:
  ```
  a_list = [(action1) if (condition1) else (action2) if (condition2) else (action3) for x in {iterable}]
  ```
"""

#@title First ladies again: run to read csv
import pandas as pd
first_ladies = pd.read_csv('https://raw.githubusercontent.com/ohspc89/reprorehab2025/students/contents/week3/first_ladies.csv')
first_names = first_ladies.First_name.to_list()
last_names = first_ladies.Last_name.to_list()

# First names of the first ladies
first_names

# What would `a_list` be like?
# 1) Append "MARTHA!" if a value of the iterable: `first_names` is "Martha"
# 2) Append "Dr.Biden" elif a value of the iterable: `first_names` is "Jill"
# 3) Append None if a value of the iterable is neither "Martha" nor "Jill".
# Therefore, the list comprehension after `None` will have only three possible values:
#   "MARTHA!", "Dr.Biden", and `None`.
a_list = ["MARTHA!" if x == "Martha" else "Dr.Biden" if x == "Jill" else None for x in first_names]
# `filter` is a function that can filter elements.
# Here, we're filtering out `None` from `a_list`, just to remove many `None`.
list(filter(None, a_list))

"""### match/case

This is a new feature in Python >=3.10 - useful when your are interested in matching patterns.
"""

test_list = list()
for name in first_names:
  match name:
    case "Martha":
      test_list.append("MARTHA!")
    case "Jill":
      test_list.append("Dr.Biden")
    # Similar to if-elif-else, you can skip 'else' condition
    # you can use '_' - this is similar to `else`
    case _:
      continue  # move on

test_list

"""## Loops (for/while)

By now who have seen many `for` loops. The idea is simple, so here I'd like to introduce methods that can go well with a `for` loop.

- `enumerate()`: adds a counter
- `zip()`: takes multiple {iterables} and aggregates their elements to a tuple.
"""

# enumerate - if you need a counter
for i, col in enumerate(first_ladies.columns):
  print(f"Column {i+1}: {col}")

for j, row in enumerate(first_ladies.values):
  # `not` reverses the boolean value, so `not False` is `True`.
  # Therefore, we're only considering cases of `j % 10 == 0`
  # `!=` means "not equal to"
  if (not j % 10) and (j != 0):
    # We're still using `first_ladies`, so printed row content will be:
    # 'fist name', 'last name', 'maiden name', 'year_start', 'year_end'
    print(f"row {j}: {row}")

# zip(A, B, ...)
# At each iteration, elements of `first_names` and `last_names` will be
# aggregated into a tuple (ex. ('Martha', 'Waghington'))
for full_name in zip(first_names, last_names):
  print(f"First name: {full_name[0]}; last name: {full_name[1]}")

"""### break/continue

`break` will break the loop. `continue` is to move to the next iteration without any action performed.
"""

# break a loop in the middle
# `first_names` has 48 elements, so `i` can iterate over range(48)
for i, name in enumerate(first_names):
  if name == "Nancy":
    print(f"Nancy found! Closing the loop at the iteration: {i}")
    # iteration terminates when `name == "Nancy"`
    break
  else:
    # If `name == "Nancy"` is False, do nothing and move to the next iteration.
    continue

"""### Use `while` when you don't know the number of iterations needed.

`for` loops will end when it reaches the last iteration index. If you need to loop while a condition is `True`, use `while`.
"""

# Let's suppose you don't know the index of the first name "Lucretia" in the list: `first_names`

to_lookfor = 'Lucretia'
i = 0   # A start index is typically set to 0 - the starting index
while first_names[i] != to_lookfor:
  i += 1    # `i += 1` is the shorthand of `i = i + 1`

# Remember, Python starts counting from 0, not 1
print(f"{to_lookfor} is the {i+1}th first name")

# While loop can be "broken" as well

k = 0
counter = 0
# Don't do this - it can lead to an infite loop...
while True:
  if first_names[k] == "Martha":
    counter += 1
  # If "Martha" is found twice, break the loop
  if counter == 2:
    break
  k += 1

print(f"The second 'Martha' is found in row: {k}")

"""You may want to provide a safe guard to avoid infinite loops if your code is not correctly written.

```
max_iter = 1000  # limit the number of iterations
steps = 0

while True:
    ...  # whatever action you want to loop over
    steps += 1  # increase the counter
    # if the loop iterates over `max_iter` times,
    # it will raise an error:
    if steps > max_iter:
        raise RuntimeError("Possible infinite loop-check your logic.")
```

## If you have convoluted / nested logics, use **for** loops. Whenever possible, however, use **comprehensions** or even **vectorized** methods provided by *numpy* or *pandas*.

Your code may look *longer*, but it will be *faster* if your data is BIG.
"""

# Every 10th rows?
first_ladies.iloc[[x for x in range(10, len(first_ladies), 10)], :]

# Lucretia, 20th first name
# Remember `.str.match()`?
first_ladies[first_ladies["First_name"].str.match("Lucretia")].index

# Let's suppose you have a n-by-3 accelerometer reading.
import numpy as np

# `.tolist()` is a numpy ndarray's method -> make a list
N = 100
sample_acc_x = (np.random.random(N) + 9.8067).tolist()
sample_acc_y = (np.random.random(N)).tolist()
sample_acc_z = (np.random.random(N)).tolist()

# Let's think about calculating the root mean square: sqrt(x**2 + y**2 + z**2)

# to assess performance
from time import time

# Ok, so we learned how to use `zip` with a `for` loop!
acc_rms_for = list()
for acc in zip(sample_acc_x, sample_acc_y, sample_acc_z):
  acc_rms_for.append(float(np.sqrt(acc[0]**2 + acc[1]**2 + acc[2]**2)))

# Numpy already has `numpy.linalg.norm()` method.
# First prepare N-by-3 ndarray.
acc_xyz = np.hstack((np.array(sample_acc_x).reshape(-1, 1),
                     np.array(sample_acc_y).reshape(-1, 1),
                     np.array(sample_acc_z).reshape(-1, 1)))

# Single line
acc_rms_np = np.linalg.norm(acc_xyz, axis=1)

#@title Benchmark
from time import time

def loop_performance(x, iter=100):
  op_times = list()
  for _ in range(iter):
    tic = time()
    acc_rms_for = list()
    for acc in zip(x[0], x[1], x[2]):
      acc_rms_for.append(float(np.sqrt(acc[0]**2 + acc[1]**2 + acc[2]**2)))
    op_times.append(time() - tic)
  return (np.mean(op_times), np.std(op_times))

def numpy_performance(x, iter=100):
  op_times = list()
  for _ in range(iter):
    tic = time()
    acc_rms_np = np.linalg.norm(x, axis=1)
    op_times.append(time() - tic)
  return (np.mean(op_times), np.std(op_times))

# Mean processing time for N = 100: ~2e-4
loop_performance((sample_acc_x, sample_acc_y, sample_acc_z))

# Mean processing time for N = 100: ~9.7e-6
# About x100 faster than `for` + `zip`
# This gap will only increase as your dataset size increases.
numpy_performance(acc_xyz)

"""## Functions

Start when you see typing the same operation again and again.

At some point, you will start by preparing bunch of functions before conducting an actual analysis (modularization).

The structure of a function is this:
```
def some_function(parameter):
  what a function does
```
"""

# Functions may not have any parameters (=arguments).
def print_hello():
  print("Hello!")

print_hello()

# Function parameters can have default values:
# Here, default values of the specified by:
#   `(name of a parameter)=(default value)`
# So here, the default of `num1` is `None`. The same is true for `num2`.
def add_nums(num1=None, num2=None):
  # `all(iterable)` returns True if everything in iterable is True.
  # So here, if `num1` is None and `num2` is None, it will be True
  if all((num1 is None, num2 is None)):
    # If conditional is True, return `None`.
    # A function 'ends' with a `return` command.
    return None
  # This is why you don't need explicit `else` statement here.
  # If `if` statement above is true, there's already an associated `return` statement,
  # so the function will no longer proceed. If `if` statement is not true,
  # following `return` statement will run.
  return num1 + num2

# This returns None, because no `num1` or `num2` value is provided.
# Both parameters will be `None`, and the function will return `None`
#   -> so you don't see anything returned
add_nums()

# If `num1` is not None or `num2` is not None, `num1 + num2` is returned.
add_nums(3, 7)

"""There's one more concept here: *type hints*. Type hints are annotations that specify the expected data types for variables and function parameters, improving code readability and helping to catch errors before runtime.

Type hints are provided using `:`.
```
def some_function(param:str):
    ...
    return ...
```
Now the function `some_function` will expect a parameter `param` to be a string. However, even if you provide a different data type, it will still proceed. Again, *type hints* are mostly for readability.

"""

def some_function(param:str):
  return f'param is string: {isinstance(param, str)}'

some_function(3)

# Both a hint and a default value can be provided simultaneously.
def print_names(name:str="Jin"):
  return f"Your name is: {name}"

# This will use the default parameter value: "Jin"
print_names()

# You can also provide other parameter values
print_names("Rumi")

# Type hint choice can be more than one - use OR(|) operator
def multiple_type_hints(param:int|float=3.0):
  return param

# This will return the default value: 3.0
print('param default data type: int (=3)')
print(multiple_type_hints())
print('-----------------------------------')
print('param data type: int (=7)')
print(multiple_type_hints(7))
print('-----------------------------------')
print('param data type: float (=2.781)')
print(multiple_type_hints(2.781))
print('-----------------------------------')

# Hints are useful when users are not sure of what parameters to give
# to a function. You can read that the function: `print_names` expect
# a string input.
help(print_names)

"""### Docstring

A docstring is a string literal that occurs as the first statement in a module, **function**, class, or method definition.

Use `triple double quotes (''')` around a docstring.

- Single line docstring: `'''this is a docstring.'''`
- Multiple line docstring:\
  ```
  '''
  This is a multi-line docstring.
  Right?
  Yeah right.
  '''
"""

# It's also recommended that you provide 'docstring'.
# A docstring is marked by ''' or """

# Example:
def fortune_teller(question:str|None=None):
  """
  This is a docstring prepared following the NumPy style.
  There are other types: Google style, Sphinx style

  fortune_teller is a function that tells you the answer
  to the greatest question of Life, the Universe, and Everything.

  Parameters
  ----------
  question: str|None
    User's question; default to None

  Returns
  -------
  42 (ref. The Hitchhiker's Guide to the Galaxy)
  """
  return 42

fortune_teller()

# Again, check out the norm
help(np.sum)

"""### Nested function / inner function

You can define a function inside a function. Of course, it will be local to the *outermost* function.
"""

def nested_function(val:list|None=None):
  """
  nested_function will show how you can nest a function
  inside another function.

  If `val` is not a list, return None.
  Otherwise, return a new list with each element doubled.

  Parameters
  ----------
  val: list|None (this means the expected input for `val` is either a list or None)
    a list to process; default to None

  Returns
  -------
  None if val is None, double_it(val) otherwise.
  """
  if not isinstance(val, list):
    return None

  def double_it(to_double:list):
    """Double the elemenfs of a provided list"""
    return [x * 2 for x in to_double]

  return double_it(val)

nested_function([1,2,3,4,5])

"""### A function can return multiple values"""

def return_two_values(val:list):
  """
  return_two_values will return the original list(val)
  and the squared values of the original list.

  Parameters
  ----------
  val: list
    a list to process

  Returns
  -------
  val, squared values of val
  """
  return val, [x**2 for x in val]

# You can do this:
orig, transformed = return_two_values([1,2,3])
transformed

"""Many functions in fact return multiple values.

- `enumerate(iterable)`: index and value returned
  ```
  # See that i and v are returned?
  # i = 0 & v = 3 -> i = 1 & v = 4 -> i = 2 & v = 5
  for i, v in enumerate([3, 4, 5]):
      ...
  ```
- `numpy.linalg.eig(A)`: (eigenvalues, eigenvectors)
  ```
  # A = |3  4|
  #     |7 11|
  A = np.array([[3, 4], [7, 11]])
  # Eigendecomposition of the matris A
  # It will return `EigResult` which is a tuple of
  # `eigenvalues` and `eigenvectors`
  np.linalg.eig(A)
  ```
- `numpy.where(condition)`: tuple of arrays
  ```
  B = np.array([1, 3, 7, 9, 11])
  np.where(B > 5)
  ```
"""

A = np.array([[3, 4], [7, 11]])
res = np.linalg.eig(A)
res

# numpy.where (condition) will return indices where condition is True
# If an array is 1-D, it will return row indices.

# This will return (array([0, 1, 2, 3, 4]), )
# because there's no column indices
np.where([1, 2, 3, 4, 5])

# If there a matrix:
#  |0 0|
#  |3 7|
# row 1, columns 0 & 1 are non-zeros (True)
# Therefore, this function will return (array([1, 1]), array([0, 1]))
np.where(np.array([[0, 0], [3, 7]]))

# Another matrix (B):
#  |1 3 7 9 11|
#  |2 4 6 8 10|
# Numbers greater than 5 are:
# 7 (=B[0, 2])
# 9 (=B[0, 3])
# 11(=B[0, 4])
# 6 (=B[1, 2])
# 8 (=B[1, 3])
# 10(=B[1, 4])
# Therefore, the returned value will be:
#    ---row indices---           ---column indices---
# (array([0, 0, 0, 1, 1, 1]), array([2, 3, 4, 2, 3, 4]))
B = np.array([[1, 3, 7, 9, 11], [2, 4, 6, 8, 10]])
np.where(B > 5)

# 3D array?

# C[0, :] = |1 2|
#           |3 4|
# C[1, :] = |5 6|
#           |7 8|
# C[2, :] = |9  10|
#           |11 12|
C = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]],
              [[9, 10], [11, 12]]])
# Finding indices where C % 2 = 1
# Basically, finding indices of odd numbers.
# Values where the condition is True are:
# 1 (=C[0, 0, 0])
# 3 (=C[0, 1, 0])
# 5 (=C[1, 0, 0])
# 7 (=C[1, 1, 0])
# 9 (=C[2, 0, 0])
# 11(=C[2, 1, 0])
# Then the returned indices will be:
# (array([0, 0, 1, 1, 2, 2]),
#  array([0, 1, 0, 1, 0, 1]),
#  array([0, 0, 0, 0, 0, 0]))
np.where(C % 2)