# -*- coding: utf-8 -*-
"""reading_csv_real_world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xd-xEVXZFnteyWvPF5RVmCDgsu8lA84y

# Real world example - how do you read and manipulate a csv file using Pandas?

Here we review the script to read a CSV file
"""

#@title This cell is prepared to simulate a dataset: `randomized_dataset.csv`

import pandas as pd
import numpy as np

# Set random seed for reproducibility
np.random.seed(42)

# Define IDs and columns
ids = [f"ST{i}" for i in [53,52,51,49,48,47,46,45,44,43,42,41,37,35,34,32,31,30,28,26,25]]
columns = ["Pre", "P3", "P6", "P12", "FU_3wk", "FU_6wk"]

# Generate random numbers between 0.2 and 1.5
data = np.round(np.random.uniform(0.2, 1.5, size=(len(ids), len(columns))), 2)

# Create DataFrame
df_random = pd.DataFrame(data, columns=columns)
df_random.insert(0, "ID", ids)

# Optionally, save as CSV
df_random.to_csv("randomized_dataset.csv", index=False)

# The cell above imported the package: import pandas as pd
# This file is created from the cell above - and it will be in the working directory that you're at.
filepath = 'randomized_dataset.csv'

# Ok, minimal setting. This is ok, because the file we're reading is CSV.
data = pd.read_csv(filepath)

# Let's see how it looks first.
data

# You don't need to use `print()` to display your DataFrame.
# `data.head()` is good enough.

# Original comment:
#   [subtract all columns from baseline and create new columns "data_change"]
# I guess what was meant is: create a 'new data frame', not 'new columns'?
data_change = data.copy()

# Original comment:
#   [subject columns for all post-training timepoints (P3, P6, FU_32k, FU_6wk)
#    from column 1 in data and save as new columns data_change]

# Original code
data_change['P3_change'] = data_change['P3'] - data_change['Pre']
data_change['P6_change'] = data_change['P6'] - data_change['Pre']
data_change['P12_change'] = data_change['P12'] - data_change['Pre']
data_change['FU_3wk_change'] = data_change['FU_3wk'] - data_change['Pre']
data_change['FU_6wk_change'] = data_change['FU_6wk'] - data_change['Pre']

# By all means, do not feel like the method above should be avoided.
# As I mentioned in the first pod meeting - if it works, it works.

# Preparing `data_change` again, to make sure my code works fine.
data_change = data.copy()

# I could also think of this way:
orig_column_names = data.columns[2:].to_list()
new_column_names = [f'{colname}_change' for colname in orig_column_names]
data_change[new_column_names] = data_change[orig_column_names].sub(data_change['Pre'], axis=0)

# Let's decode three lines.
# We start with understanding what the variable `orig_column_names` is.
# `pandas.DataFrame.columns` returns a `pandas.Index` object.
# In other words, what's returned is not a plain list
data.columns

# I introduced in Week2 material, but `[2:]` means all values from the 2nd index to the end of an iterable.
# The columns of `data` are:
#         ID, Pre, P3, P6, P12, FU_3wk, FU_6wk
# slice  0   1    2   3   4    5       6       7
# index    0   1    2   3   4      5       6

# This will return `Index(['ID'])`
data.columns[0:1]

# This will return `Index(['P3', 'P6', 'P12'])`
data.columns[2:5]

# As only columns 'P3', 'P6', 'P12', 'FU_3wk', and 'FU_6wk' will be changed,
# this is what we need.
data.columns[2:]

# You can use this as is, because pandas will automatically handle.
# To be super explicit, you can use `.to_list()` method to return a pure list.
# This is what's saved into a variable named `orig_column_names`.
data.columns[2:].to_list()

# Onto the next line - how is 'new_column_names' defined?
# First let's start with a plain list comprehension.
[column_name for column_name in orig_column_names]

# f-strings, for formatted-strings make string formatting and interpolation easier.
# Here's one example you can test it out.
name = 'Jin'
print(f'My name is {name}')

# Can you now see what's happening here?
# This is what's saved in `new_column_names`.
[f'{column_name}_change' for column_name in orig_column_names]

# Ok, then the final line.
# `data_copy[new_column_names] = ...` indicates that multiple columns
# (ex. P3_change, P6_change, ...) that are not yet in the DataFrame `data_copy`
# will be defined as what's described to the right of the equal sign.

# `pandas.DataFrame.sub(element)` method substracts `element` from `pandas.DataFrame`.
# We are subtracting the 'Pre' column from each column.
# `axis=0` argument tells that subtraction will occur row wise.
# For example, 'P3_change' column is prepared in the following way:

#    row 0 of `P3_change`:  P3[0] - Pre[0]
#    row 1 of `P3_change`:  P3[1] - Pre[1]
#    row 2 of `P3_change`:  P3[2] - Pre[2]
#                        ...
#    row 30 of `P3 change`: P3[30] - Pre[30]

# Remember, you must specify the value of `axis` argument,
# because its default value is not 0.
data_change[orig_column_names].sub(data_change['Pre'], axis=0)

# See for yourself - disaster here.
data_change[orig_column_names].sub(data_change['Pre'])

# Original code
data_change.mean(axis=0)

# This returns error. Why?
# You're applying the `mean` function to all columns of data_change.
# The first column, 'ID', does not contain numeric values.
# This is what the message tells you.

# You can use `.iloc`, but this would require you to "know" your data structure.
data_change.iloc[:, 1:].mean(axis=0)

# `.select_dtypes` method can be useful as well.
# Check out the return of the line below.
data_change.select_dtypes(include='number')

# Are you now convinced that this will return the expected output?
data_change.select_dtypes(include='number').mean(axis=0)

# Lines using `.std()` is the same.
# `data_change.std(axis=0)` returns an error.

# Ok, visualization.

# It's `import matplotlib.pyplot as plt`, not `import matplotlib as plt`
# I also see that you use seaborn. Yes, Seaborn package makes beautiful plots.
# I don't think I will introduce it during the first 6 weeks or so...
# May be during the last two weeks - if more people are interested in discussing data visualization more?
import matplotlib.pyplot as plt
import seaborn as sns

# Original comment
#   make a boxplot of only some of the columns not all data but only timepoints

# Original code
data_change_subset = data_change[['Pre', 'P3', 'P6', 'P12', 'FU_3wk', 'FU_6wk']]
sns.boxplot(data_change_subset)

# Long time ago, we created a variable: `orig_column_names`
# Why not reuse it?

# This returns the list you wrote by hand above.
pre_subset = ['Pre'] + orig_column_names
pre_subset

# This returns the same plot as your code, right?
sns.boxplot(data_change[pre_subset])

# Original code
data_change_subset = data_change[['P3_change', 'P6_change', 'P12_change', 'FU_3wk_change', 'FU_6wk_change']]

# Again, why not use the variable we created before?
data_change_subset = data_change[new_column_names]

# I am not lying.
data_change_subset.head(5)

# In the end, you save the modified csv file.
# You will see this file created, again in the working directory you are at.
data_change.to_csv('cleaned_dataset.csv', index=False)

# This is a good practice. If you skip including `index=False`,
# the saved CSV will have leftmost column with numbers 0, 1, ..., 30.