# -*- coding: utf-8 -*-
"""timestamps_pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bSRzKw9X5kntkJYVPzBc5bYgpCdVtO9P

# Handling time in Pandas

There may be cases where you want to make use of timestamps associated with your samples.

Python has a datatype: [`datetime`](https://docs.python.org/3/library/datetime.html). Pandas has its own version: [`Timestamp`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Timestamp.html).
"""

import pandas as pd

# Check out what's returned. Does it match your expectation?
sample_time_string = '12:34'
test_timestamp = pd.to_datetime(sample_time_string)
test_timestamp

"""`to_datetime` function requires an argument. The argument datatype can be one of the following: `int`, `float`, `str`, `datetime`, `list`, `tuple`, `1-d array`, `Series`, `DataFrame/dict-like`.

### int/float argument

You may have heard of a date and time representation called [**Unix time**](https://en.wikipedia.org/wiki/Unix_time). This is the number of non-leap seconds that have elapsed since 1970-Jan-01, 00:00:00 UTC (Coordinated Universal Time). What's the current unix time?
"""

# This returns current date and time in UTC.
pd.Timestamp.now()

# You can specify your timezone by giving the value of 'tz'
# Try your timezone!
# ex. 'US/Eastern', 'US/Mountain', 'US/Pacific',
mytz = 'America/Los_Angeles'
pd.Timestamp.now(tz=mytz)

# This returns current date and time in Unix time
unix_timestamp = pd.Timestamp.now().timestamp()
# This should be 'float'
unix_timestamp

# Can we now feed it to `to_datetime`?
# You have to specify the unit by giving `unit='s'`.
# Otherwise, it will use the default option: 'nanosecond'.

# This will give you some weird timestamp.
pd.to_datetime(unix_timestamp)

# This will return the expected timestamp.
pd.to_datetime(unix_timestamp, unit='s')

# Can we make it so that you can see the time on your computer?
pd.to_datetime(unix_timestamp, utc=True, unit='s').astimezone('America/Los_Angeles')

"""You can extract `year`, `month`, `day`, `hour`, `minute`, `second`, `microsecond` and `nanosecond`."""

ts = pd.to_datetime(unix_timestamp, utc=True, unit='s')
# Replace `.year` with another attribute (ex. `.month`)
ts.year

# Timezone can be printed, if the information exists.
ts.timetz()

"""If you only want date, use `.date()`. If you only want time, use `.time()`. If you also want timezone information, use `.timetz()`"""

ts.time()

"""### list argument

If you give a list of elements, it will return a new data type: `DatetimeIndex`. Don't forget to match the format of the inputs.
"""

list_datetimes = pd.to_datetime(['2020-02-03 13:45:27', '2022-03-01 09:12:34'])
list_datetimes

# Again, make sure you specify the unit, if you're just giving numbers.
list_datetimes2 = pd.to_datetime([1759070073, 1759710283], unit='s')
list_datetimes2

# When distinctly formatted values are provided, it will return errors.
# If your Pandas version is > 2.2.0, you can use `format='mixed'` to have
# Pandas infer format for each element.
list_datetimes_unique_format = pd.to_datetime(['2020-02-07', '2022-03-01T09:12:34'],
                                              format='mixed')
list_datetimes_unique_format

# Each element of DatetimeIndex is Timestamp.
# `list_datetimes2[0]` is '2025-09-28 14:34:33', so '.day' is 28.
list_datetimes2[0].day

"""## Well-known time formats

There are some time formats widely used by people:

1. YYYY-MM-DD hh:mm:ss (ex. 2021-09-18 07:23:17)
2. YYYY/MM/DD hh:mm:ss (ex. 2024/03/01 14:11:00)
3. YYYY-MM-DD**T**hh:mm:ss (ex. 2025-07-25T13:23:12)

Otherwise, you have to provide what's the format of the string you are providing.
"""

# Custom formatting
# %Y: year | %m: month | %d: day | %H: hour | %M: minute | %S: second
pd.to_datetime('2020-09-26_17:25', format='%Y-%m-%d_%H:%M')

# another example - Series as an input
ts_series = pd.Series(['20200725-132436', '20200825-093725'])
# returns a series
pd.to_datetime(ts_series, format='%Y%m%d-%H%M%S')

"""## Do-It-Yourself

Let's suppose you have a dataframe in this format:

```
+--------------+-----+--------------------+--------------------+
|participant_id|group|timepoint1          |timepoint2          |
+--------------+-----+--------------------+--------------------+
|sub-001       |A    |2020-07-03T13:05:02 |2020-07-04T12:58:22 |
+--------------+-----+--------------------+--------------------+
|sub-002       |A    |2020-08-02T15:11:00 |2020-08-03T14:59:37 |
+--------------+-----+--------------------+--------------------+
|sub-003       |B    |2020-07-11T08:15:02 |2020-07-12T08:11:25 |
+--------------+-----+--------------------+--------------------+
|...           |...  |...                 |...                 |
+--------------+-----+--------------------+--------------------+
"""

# Read the file
dt = pd.read_csv('https://raw.githubusercontent.com/ohspc89/reprorehab2025/students/contents/week2/sample_timestamps_dataset.csv')
dt.head()

# What are the datatypes of the elements of timepoint1 and timepoint2 columns?
# Can you check the data type of the first element of timepoint1? Use `type` function.
type(...)

# Let's first check if the time difference between two points are ~ 24 hours

# Let's convert timepoint columns to 'datetime' series.
# Remember, this is how you would convert string
pd.to_datetime(dt['timepoint1'])

# So your code can be...
dt['timepoint1'] = ...
dt['timepoint2'] = ...

# Check if you've done it right - this should return a Timestamp object.
dt['timepoint1'][0]

# You can use `.apply` method to apply `pd.to_datetime` function to each column
# Check out this example.

# sample function - this adds 2 to a number
def add_two(x):
  return x+2

toy_df = pd.DataFrame({'A': [1, 2, 3], 'B': [2.0, 7.0, 9.0]})
# Can you understand how does `.apply` work?
toy_df.apply(add_two)

# Now let's expand your skill.
# First we will convert columns back to strings, assuming you converted them in the previous cell.
# This line you don't need to 'understand' for now...
dt[['timepoint1', 'timepoint2']] = dt[['timepoint1', 'timepoint2']].apply(lambda s: s.dt.strftime('%Y-%m-%dT%H:%M:%S'))

# Ok, then now it is your turn.
dt[['timepoint1', 'timepoint2']] = ...

# This should again return a Timestamp object.
dt['timepoint1'][0]

# Ok, now you can subtract two timestamps.
# Let's create a new column, 'time-delta'
dt = dt.copy()
dt['time-delta'] = ...

# This should now return a data frame with a new column: 'time-delta'
dt

# Right now, 'time-delta' is displayed as 'X days HH:MM:SS'
# You can use this trick to convert the value in hours.
dt['time-delta'] = dt['time-delta'] / pd.Timedelta(hours=1)
# You can check if the conversion was properly made
dt

# Finally, you can use '.mean()' method to get the average of 'time-delta'
# and see if the mean difference between two timepoints is ~24 hours.
mean_difference = ...
print(mean_difference)

# Can you update 'time-delta' so that numbers will be rounded up to the two decimal points?
# You can use `.round()` method.
dt['time-delta'] = ...

# How about using `.describe()` method to see more of 'time-delta' column?
...

# How about we visualize if groups are similar with respect to time difference?
# Let's make a boxplot using `pandas.DataFrame.boxplot()`.
# X-axis: group
# Y-axis: time-delta
# Your X-axis item will be passed as the value of `by` argument.
# Your Y-axis item will be passed as the value of `column` argument.
# In addition, please give `xlabel` and `ylabel` arguments appropriate values:
#    'Group' and 'Time difference (hours)', respectively.
# dt.boxplot(column='time-delta', by='group', xlabel='Group', ylabel='Time difference (hours)')
dt.boxplot(column=...,
           by=...,
           xlabel=...,
           ylabel=...)