# -*- coding: utf-8 -*-
"""Visualization-seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzgobOyJnRanKoinXQj6qQzOT8sRXeS2

# Seaborn package

Here you will read Medium pages written by [Rahul Raoniar](https://www.rahulraoniar.com/).

- [page 1](https://medium.com/the-researchers-guide/generate-publication-ready-plots-using-seaborn-library-part-1-f4c9a6d0489c)
- [page 2](http://medium.com/the-researchers-guide/generate-publication-ready-facet-pair-and-joint-plots-using-seaborn-library-part-2-4a2a6f2f491a)

Then you will generate several figures using seaborn's functions after cleaning data first.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import matplotlib.dates as mdates, zoneinfo
import seaborn as sns

"""We will plot EEG data ([source](https://physionet.org/content/auditory-eeg/1.0.0/Raw_Data/#files-panel)).

Data were sampled with 200 Hz sampling rate, and each recording was ~ 2 minutes. 200 x 60 x 2 = 24,000 samples. This is raw data we're reading, so there are more samples than that.
"""

# This may take some time...
url = 'https://physionet.org/files/auditory-eeg/1.0.0/Raw_Data/s01_ex01_s01.txt?download'
raw_eeg = pd.read_csv(url)

# Some column names contain leading whitespace.
# TODO: Please rename the columns with all whitespace removed.
# Please do so using a single line. See slide 18 of week 2 material.
# Include these arguments in the function:
#    - columns: a dictionary with original column names as keys
#               their leading whitespace removed as values
#    - inplace: a correct boolean value
# When preparing the value for the `columns` argument,
# you can use a dict comprehension + `.strip()` function.
raw_eeg.rename(...)

# This is one example showing what `.strip()` does.
' hello my name is Jin '.strip()

# We want to check if data were sampled really at 200Hz.
# If that is true, the time interval between two adjacent points
# should be 1/200 = 0.005 seconds.

# Let's first make a new column: 'dT'
# `pandas.Series.diff()` will calculate the difference between two adjacent values
# in a series. Complete the line below.
raw_eeg['dT'] = raw_eeg['Timestamp'].diff()

# Now plot the distribution of 'dT'.
# The Medium webpage introduces the use of `seaborn.displot`.
# However, this is a figure-level function, so it cannot fit into subplots.
# Instead, we will use separate functions: `.histplot`, `.kdeplot`, `ecdfplot`.
fig, ax = plt.subplots(2, 2, constrained_layout=True)

# TODO: Plot four figures
# Plotting the histogram
sns.histplot(..., ax=ax[0, 0])
# Plotting the histogram with the density curve
sns.histplot(..., stat='density', ax=ax[0, 1])
sns.kdeplot(..., ax=ax[0, 1], color='C1')
# Plotting the density curve only
sns.kdeplot(..., ax=ax[1, 0])
# Plotting the ECDF plot
sns.ecdfplot(..., ax=ax[1,1])

# Ah, seems like the sampling rate was not always 200Hz.
# It's apparent that sampling clock jitter was present.
# TODO: How about we get the 'description' of the column 'dT'?
...

# Wait, but min(dT) is 0.0? So we have 'identical' timestamps?
same_dt = raw_eeg['dT']==0.0
# Example: rows 1 & 2 have identical timestamps
raw_eeg.iloc[0:4, :]

# @title Helper function: `spread_duplicates_timestamps`
def spread_duplicates_timestamps(df, ts_col='Timestamp', fs=200, atol=1e-6, min_step=1e-6):
  df = df.copy()
  ts = df[ts_col].to_numpy(dtype=np.float64)
  N = len(ts)
  i = 0
  while i < N:
    j = i + 1
    # identical timestamp block
    while j < N and np.isclose(ts[j], ts[i], atol=atol):
      j += 1
    n = j - i
    if n > 1:
      if j < N:
        t0, t1 = ts[i], ts[j]
      else:
        t0, t1 = ts[i], ts[i] + n * (1/fs)
      ts[i:j] = np.linspace(t0, t1, num=n, endpoint=False)
    i = j
  dt = np.diff(ts)
  bad = dt < min_step
  if bad.any():
    eps = np.cumsum(bad) * min_step
    ts[1: ] += eps
  df[ts_col] = ts
  return df

# Run this line to 'correct' the timestamps
raw_eeg2 = spread_duplicates_timestamps(raw_eeg)

# Let's make a new histogram to see the distribution of new timestamps' intervals
# Fist you need to update the column: dT
raw_eeg2['dT'] = raw_eeg2['Timestamp'].diff()

# Then draw a displot showing the distribution of new intervals using sns.distplot
sns.displot(...)

# Oh, the xticklabel is a bit confusing. Let's edit.

# `g = sns.displot(...)` saves entire information about the plot
# to a variable `g`.
# You can then access the properties of the plot through `g`.
g = sns.displot(data=raw_eeg2, x='dT', kind='hist')
# Accessing `xaxis` of `ax` attribute of `g`.
# Then use `.set_major_formatter` to set the format
# `ticker.FuncFormatter(lambda x, _: f"{x:.6g}")` helps you with displaying
# numbers using 6 significant figures.
g.ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f"{x:.6g}"))
# This is how you 'rotate' the tick labels
g.ax.tick_params(axis='x', rotation=45)
# This is how you set the title.
g.fig.suptitle("Timestamp intervals (dT)", x=0.6, fontstyle='italic')
# Setting the x-axis label
g.ax.xaxis.set_label_text('dT (s)', weight='bold')
# y-axis label?
g.ax.yaxis.set_label_text('Count', size=18)

# Ok, then let's regenerate datetime from timestamps.
# Data were recorded at Marche Polytechnic University.
# This university is in Italy
raw_eeg2['Timestamp (Formatted)'] = pd.to_datetime(raw_eeg2['Timestamp'], unit='s', utc=True)
raw_eeg2['Timestamp (Formatted)'] = raw_eeg2['Timestamp (Formatted)'].dt.tz_convert('Europe/Rome')

# Let's first plot the first 100 samples of 'EXG Channel 1',
# using the associated datetime labels (formatted).

# Seaborn doesn't seem to handle datetime objects very well, so we will again
# save the figure to a variable `g2` and modify tick labels manually
# TODO: Please complete the line below.
g2 = sns.lineplot(data=..., x=..., y=...)

rome_tz = zoneinfo.ZoneInfo('Europe/Rome')
g2.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M:%S.%f', tz=rome_tz))
g2.xaxis.set_major_locator(mdates.AutoDateLocator())
g2.tick_params(axis='x', rotation=45)
# Print the date at the x-axis
date_label = raw_eeg2['Timestamp (Formatted)'].dt.date.iloc[0]
g2.set_xlabel(f"Data collection Date: {date_label}")
# This is how you remove spines at the top and the right of the figure
sns.despine(top=True, right=True)

"""## Do It Yourself

Seaborn originally preferred **long (tidy)** format. In modern versions it also accepts **wide** format. Below you will try both approaches.

### Long format

You will make a DataFrame with the following structure:

```
+--------------+-------------------------------------+---------------+------------+
| Timestamp    | Timestamp (Formatted)               | Channel       | value      |
+--------------+-------------------------------------+---------------+------------+
| 1.620206e+09 | 2021-05-05 11:13:45.084719896+02:00 | EXG Channel 0 | 544.662170 |
+--------------+-------------------------------------+---------------+------------+
| ...          | ...                                 | ...           | ...        |
+--------------+-------------------------------------+---------------+------------+
| 1.620206e+09 | 2021-05-05 11:16:52.464719772+02:00 | EXG Channel 3 | 330.104126 |
+--------------+-------------------------------------+---------------+------------+
| ...          | ...                                 | ...           | ...        |
+--------------+-------------------------------------+---------------+------------+
"""

# This is what's covered in week 3 material!
# TODO: Please complete the line below.
raw_eeg_long = pd.melt(raw_eeg2, id_vars=...,
                       value_vars=...,
                       var_name=...)
# Check if your long format is correctly prepared
raw_eeg_long

# First 100 samples of each channel - use this dataset to plot in the next cell.
first_100s = raw_eeg_long.groupby(by='Channel').head(100)

# TODO: Please complete the line below .
g3 = sns.lineplot(..., hue='Channel')

# Lines used in the previous example to format x-axis tick labels
# and x-axis label.
rome_tz = zoneinfo.ZoneInfo('Europe/Rome')
g3.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M:%S.%f', tz=rome_tz))
g3.xaxis.set_major_locator(mdates.AutoDateLocator())
g3.tick_params(axis='x', rotation=45)
date_label = first_100s['Timestamp (Formatted)'].dt.date.iloc[0]
g3.set_xlabel(f"Data collection Date: {date_label}")
sns.despine(top=True, right=True)

"""### Wide format

Just take the subset of the original DataFrame: raw_eeg2. Leave the following columns: 'Timestamp (Formatted)', 'EXG Channel 0', 'EXG Channel 1', 'EXG Channel 2', 'EXG Channel 3'

Then set the 'Timestamp (Formatted)' as the index of this new DataFrame.

```
+-------------------------------------+---------------+---------------+---------------+---------------+
| Timestamp (Formatted)               | EXG Channel 0 | EXG Channel 1 | EXG Channel 2 | EXG Channel 3 |
+-------------------------------------+---------------+---------------+---------------+---------------+
| 2021-05-05 11:13:45.084719896+02:00 | 544.662170    | -1009.462585  | 464.362793    | 351.657196    |
+-------------------------------------+---------------+---------------+---------------+---------------+
| ...                                 | ...           | ...           | ...           | ...           |
+-------------------------------------+---------------+---------------+---------------+---------------+
"""

# TODO: assign the variable below
only_channels = ...
only_channels.set_index('Timestamp (Formatted)', inplace=True)

# TODO: Use the first 100 rows of `only_channels`
g4 = sns.lineplot(...)

rome_tz = zoneinfo.ZoneInfo('Europe/Rome')
g4.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M:%S.%f', tz=rome_tz))
g4.xaxis.set_major_locator(mdates.AutoDateLocator())
# TODO: Rotate 45 degrees
g4.tick_params(...)
# Note that `date_label` is defined slightly differently.
date_label = only_channels.index.date[0]
g4.set_xlabel(f"Data collection Date: {date_label}")
# TODO: De-spine, top and right
sns.despine(...)

"""### FacetGrid

Let's also practice making separate plots for channels using `seaborn.FacetGrid()`.
"""

g5 = sns.FacetGrid(data=first_100s,
                   col='Channel')
# TODO: Replace '...' with your answer.
# Please give 'Timestamp', not 'Timestamp (formatted)', as the x axis value.
g5.map(...)