# -*- coding: utf-8 -*-
"""week1-more_on_dictionary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQ053sch5dCvHLrOWPmMD0YpH8tqyYNz

Today (10/2) I had my workblock and ended up talking more about `dict`. I decided to provide more toy-examples in case people find them helpful. Run ALL cells below including the one labeld 'show code'.

# Real-world example: nested `dict`

I introduced the Healthy Brain and Child Development (HBCD) study during the research summit. Wearable sensor data are collected, and relevant metadata are saved in JSON. Here's an example of a file:

```
{
  "filename": {
    "Data Type": "string",
    "Description": "Relative paths to files."
  },
  "acq_time": {
    "Data Type": "datetime",
    "Description": "Acquisition time"
  },
  "site": {
    "Description": "Site where the session data was collected",
    "Levels": [
      "hbcdsite89",
      "hbcdsite64"
    ]
  }
}
```

Let's suppose that the file is read using `json.load()` and saved to a variable: `metadata`.
"""

# @title run this cell to simulate file read

metadata = {
    "filename": {
        "Data Type": "string",
        "Description": "Relative paths to files."
    },
    "acq_time": {
        "Data Type": "datetime",
        "Description": "Acquisition time"
        },
    "site": {
        "Description": "Site where the session data was collected",
        "Levels": [
            "hbcdsite89",
            "hbcdsite64"
            ]
        }
}

# Let's first check the variable is created. If you see an error here,
# run the cell above to this cell.
metadata

# Use `type` to check the datatype: dict
type(metadata)

"""**()**, or parentheses, serve multiple purpoes in Python. One well-known purpose is to call **functions** or **methods**. In contrast, **[]**, or square brackets, are mostly used to *index* a sequence (ex. `list`, `dict`, `tuple`...).


So `type(metadata)` in the cell above shows that a function `type` is called, with a required *argument (arg)* value, `metadata` inside parentheses. This is how you typically **call a function** (you can read more about the origin of the term from [here](https://quuxplusone.github.io/blog/2025/04/04/etymology-of-call/)).

Many functions or methods expect arguments. That is **not** always the case. Arguments are optional to some of them.
"""

# This is an example of a function not necessitating a parameter: print()
# Try running this line, not editing anything.
print("Hello")
print()
print("World")

"""You will see that `print()` does not return any error. It just prints NOTHING, because `print` does not require any argument. If nothing is provided, it prints nothing. Cool.

A `dict` object has a **method**: `keys`. This method also does not require any argument.
"""

# So putting anything inside parentheses will return a TypeError.
# It tells you that the method does not take any argument.
metadata.keys('hello')

"""Same is true for `values` or `items`."""

# Error!
metadata.values("WHAT")
# Comment out the line above and uncomment the line below and check for yourself
# metadata.items("WHY")

"""Note that `metadata` itself is not a **function**. This means that everytime you try to use **()** with `metadata` you will see `TypeError`. The error message reads: `'dict' object is not callable`. In plain human language, that means: `'dict' is not a function`."""

metadata('hello')

"""Ok, but you can index a `dict`. **Indexing** can be understood as 'accessing an element using an appropriate index of that element'. As a `dict` is a collection of `key` and `value` pairs, you use the value of a `key` to access the `value` associated with the `key`."""

# What are the keys?
metadata.keys()

# Let's access the value of 'site'
# You now need to use square brackets, not parentheses!
metadata['site']

"""I digress, but a `list` or a `tuple` would use the position of an element (any integer number between 0 and `the length of a sequence - 1`) as an index. See the example below:"""

sample_list = [1, 2, 3, 4, 5]

# Let's suppose I want to access the second (index = 1) element of this list.
# Here's how you do it:
sample_list[1]

# This will return IndexError: list index out of range.
# 6 is greater than the length of (`sample_list` - 1) or 4.
sample_list[6]

# Same is true for tuples.
sample_tuple = (1, 2, 3)
sample_tuple[2]

"""Let's now talk about how to move into inner levels of a nested `dict`. Our `metadata` is a two-level `dict`. This means that ALL values associated with the outermost level keys (which you check by `metadata.keys()`) are also `dict`s."""

# A value of a `dict` is another `dict` with keys: 'Description', 'Levels',
# and values: 'Site where the session data was collected', ['hbcdsite89', 'hbcdsite64']
metadata['site']

"""If you want to access values of this new `dict`, you continue using **[]** with appropriate key inside them."""

# This is equivalent to `(metadata['site'])['Levels']`
# Yes, this is another purpose `()` serves: separating a chunk of a code.
metadata['site']['Levels']

"""We discussed that a value of a `dict` can be a number (ex. 1, 2.3), a string (ex. 'Hello!'), a list (ex. [1, 2, 3]) or a dict (ex. {'new_key':'new_value'}). Here the value associated with the inner key 'Levels' is a list with two string elements.

If you want to access the second element of this value, how would you do that?
"""

# If you understand this line, you're good to go.
metadata['site']['Levels'][1]