# -*- coding: utf-8 -*-
"""week1-extra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nxesF9PkmnbFwuOQcohb9YdagcX5g6mD

# Regular expression (`regex`) in Python

Python's `re` package helps users match patterns within strings.
"""

# Import the package
import re

"""Useful patterns include:
- `\d` : Matches a **digit**.
- `\w` : Matches any **word** (alphanumeric and underscore) character.
- `\s` : Matches any **whitespace** characters.
- `*` : Matches **zero or more** occurrences of the preceding character or group.
- `+` : Matches **one or more** occurrences.
- `^` : Matches **the beginning** of a string.
- `$` : Matches **the end** of a string.
- `[]`: Defines a character set.

## Checking filenames with `re.compile(pattern)`

You prepare a pattern and use it repeatedly.
"""

# Toy example 1:
sample_str = 'My name has 7 letters.'
# Let's suppose you know that there's a single digit in this string,
# but don't know where in the string.
# If you want to identify the single digit..
pat = re.compile(r'\d')   # a pattern: single digit

"""There are different methods to identify the pattern in the string. If you want to search **the first** occurrence of the pattern in the string, use `search` method."""

pat.search(sample_str)

"""Check the returned output. It's an `object`. We will talk more about in the later weeks. For now, check other values.

For example, `span` is `(12, 13)`. This means the pattern was found between the 12th and the 13th *slices* of the string (refer to slide 27 of 'Tabular data manipulation in Python I).

`match` is `7` - and this is what we've been *searching* for!

What if there's more than one occurrence and you want to *find all* of them? You can use `findall` method.
"""

# Toy example 2-a:
sample_str2a = 'Seven is not equal to 8, and is also not equal to 6 or 9!'

# Check that all single digits are found.
pat.findall(sample_str2a)

"""Remember that our pattern (`pat`) is a single digit (`r'\d'`). It will then consider bigger numbers to be the juxtaposition of single digits. See below."""

# Toy example 2-b:
sample_str2b = 'What was the plate number? 9ABC182 or 7EFG872?'

# What would this return now?
pat.findall(sample_str2b)

# This is where you need '+'
pat_multi_digit = re.compile(r'\d+')

pat_multi_digit.findall(sample_str2b)

"""Do you like it so far? Ok, How about we find the full plate numbers, not just numbers from the previous sentence? This is where `[]` would be useful."""

# [a-z]: any lowercase character
# [A-Z]: any uppercase character
# [a-zA-Z]: any character
# [0-9]: any digit

# You can use [\w] or [\d].
# Remember, [\d] is equivalent to [0-9],
# but [\w] is equivalent to [A-Za-z0-9_]

# {n}: n occurrences of lowercase character
#   ex. \d{3}: three digits; \[a-z]{3}: three lowercase characters

# Toy example 3-a:
pat_new = re.compile(r'\d[A-Z]{3}\d{3}')
pat_new.findall(sample_str2b)

# Toy example 3-b:
# This will return the same result as before,
# single digit, one or more word characters, then one or more digits.
pat_new2 = re.compile(r'[\d][\w]+[\d]+')
pat_new2.findall(sample_str2b)

# However, there is a reason to be more specific:
trick_sentence = 'In California, 3AXY697 is one possible plate number. 5Y20947 is another example.'
# Look carefully - we only want '3AXY697' to be found, but '5Y20947' is also returned.
# This is because [\w] is equivalent to [a-zA-Z0-9_] (i.e., alphanumeric and underscore).
pat_new2.findall(trick_sentence)

"""Ok, so enough with toy examples. Let's play with mock filenames."""

# Let's suppose we want to make sure that all filenames are in the right format:
#     'sub-{subject_number}_ses-{session_number}_acq-primary_motion.tsv'

# {subject_number} is a zeropadded three digits (001-999).
# {session_number} is a zeropadded two digits (01-09).

filenames = ['sub-012_ses-01_acq-primary_motion.tsv',
             'sub-372_ses-01_acq-primary_motion.tsv',
             'sub-08_ses-02_acq-primary_motion.tsv',  # {subject_number} padding incorrect
             'sub-917_ses-4_acq-primary_motion.tsv']  # {session_number} padding incorrect

"""### Example: Problem solving

As discussed in the summit, let's think about how to tackle this problem.

A. What do we have?

1. A list of filenames.

B. What do we know?

1. The correct filename should follow this format:
`'sub-{subject_number}_ses-{session_number}_acq-primary_motion.tsv'`

C. What do we want?

1. To identify filenames that are **not** formated correctly.

D. What do we need then?

1. A pattern!

2. An iterative check

    2a. A way to check each filename to see if it matches the correct format.

    2b. A way to *save* the filenames that do **not** match the correct format.

We can use `re.fullmatch` method and a **list comprehension** to address D2. Your task is to address D1.

#### Find the pattern
"""

# Task 1: compile the right pattern.
# Replace '...' with the right pattern.

# Reminders:
# 1) \w is equal to [a-zA-Z0-9_], so hyphen is not covered by \w
# 2) We 'know' that 'sub' and 'ses' are unique identifiers that will be present
#    in all file names. We're concerned if the 'numbers' following those terms
#    are formatted correctly. If so, you pattern can be simplified by including
#    'sub' and 'ses' directly (ex. r'sub-..._ses-..._')
# 3) Once you tried the option above, then you can go bold and play with \w to
#    find a more 'generalizable' pattern.
pattern1 = re.compile(r'..._acq-primary_motion.tsv')

# Next, let's check filenames iteratively using a list comprehension.
# `pattern1.fullmatch(string)` returns a `match object` if `string` matches `pattern1`.
# - In Python, any non-NULL object evaluates to True.

# Run this example to check:
pattern1.fullmatch('sub-172_ses-03_acq-primary_motion.tsv')

# Task 2: Write a list comprehension that collects filenames which do *not* match.
# Refer to slide 17 of 'Getting started with Python'
incorrect_fnames = [fname for fname in ... if ... pattern1.fullmatch(...)]
print(incorrect_fnames)