# -*- coding: utf-8 -*-
"""Plotting_with_Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_CTyfE46C1apkWy8l_0joWgNGkrFJUr

# What you'll learn:
- How to build publication-ready plots step-by-step
- Why we use "ax-first" (fig, ax = plt.subplots()) for clarity
- How to compare distributions with different histogram styles
- How to control layouts with GridSpec when subplots aren't enough

# Why this matters:
Good figures answer specific questions quickly and reproducibly. We'll annotate, style, and save with the same pattern each time.

## Contents
- [Setup](#setup)
- [Basics](#basics)
- [Subplots & Layouts](#subplots--layouts)
- [Customized Layouts](#customization)
- [Common Pitfalls & Tips](#common-pitfalls--tips)

## Setup
<a id='setup'></a>
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# If we want to customize sizes of axes, use 'GridSpec'
from matplotlib.gridspec import GridSpec

# Read more from "https://physionet.org/content/gaitpdb/1.0.0/#files-panel"
data = pd.read_csv('https://physionet.org/files/gaitpdb/1.0.0/GaCo01_01.txt?download',
                   sep='\t', header=None,
                   names=['Time',
                          *[''.join(('LS', str(p))) for p in range(8)],
                          *[''.join(('RS', str(q))) for q in range(8)],
                          'Total_LS', 'Total_RS'])

data.columns

"""We're reading one file from the dataset that contains measures of gait from 93 patients with idiopathic PD and 73 healthy controls. 'GaCo01_01' should be the data from a control subject.

The database includes the vertical ground reaction force records of subjects as they walked at their usual, self-selected pace for approximately 2 minutes on level ground. Underneath each foot were 8 sensors that measure force (in Newtons) as a function of time (`LS0`, `LS1`, ..., `RS6`, `RS7`). The output of each of these 16 sensors has been digitized and recorded at 100 samples per second, and the records also include two signals that reflect the sum of the 9 sensor outputs for each foot (`Total_LS` and `Total_RS`).

# Modifying axis properties

- Title (`ax.set_title(...)`)
- X/Y axis label (`ax.set_xlabel(...)`, `ax.set_ylabel(...)`)
- Spines (`ax.spines(...).set_visible(bool)`)
- Extra line (`ax.axvline(...)`, `ax.axhline(...)`)
- X/Y axis limit (`ax.set_xlim(...)`, `ax.set_ylim(...)`)
- Text (`ax.text(...)`)

## Basics
<a id='basics'></a>
"""

# Let's plot the recording of the left foot's first sensor('LS0')
fig, ax = plt.subplots(1, 1, figsize=(12, 4))
ax.plot(data['Time'], data['LS0'])

# Let's set a title: "First Left Sensor (fs: 100Hz)"
# You can use `ax.set_title(...)`
ax.set_title("First Left Sensor (fs: 100Hz)", fontsize=20)

# Let's also set X-axis label as "Time (s)" and Y-axis label as "Force (N)".
# You can use `ax.set_xlabel(...)` and `ax.set_ylabel(...)`
ax.set_xlabel("Time (s)", fontsize=14)         # set fontsize to 14
ax.set_ylabel("Force (N)", fontweight='bold')  # make text 'bold'

# What about removing 'top' and 'right' spines?
ax.spines[['top', 'right']].set_visible(False)

# Let's add vertical lines at 20, 40, 60, 80, 100, and 120s
vertical_line_xcoord = [20, 40, 60, 80, 100, 120]
for xc in vertical_line_xcoord:
  ax.axvline(x=xc, ymin=0, ymax=1, linestyle='dashed', color='C1')

# Let's also add a horizontal line at y=200
ax.axhline(y=200, xmin=0, xmax=1, color='r')

# Setting axis limit - let's use `ax.set_ylim(bottom, top)` to set y-axis limit.
# Set bottom=0, and top=650. X-axis limit can also be set with `ax.set_xlim(bottom, top)`.
ax.set_ylim(0, 650)
ax.set_xlim(10, 110)

# We can add texts. Let's add the length of this timeseries.
# Use `ax.text(x, y, s)`. We can use x=82, y=500, s=f"{len(data['Time'])}"
ax.text(82, 500, f"Total: {len(data['Time'])} samples")

"""# Subplots with fixed aspect ratio

*Goal*: Compare distributions under different histogram settings; learn what `bins`, `density`, and stacking actually do.

## Subplots & Layouts
<a id='subplots--layouts'></a>
"""

# Read more from https://physionet.org/content/rr-interval-healthy-subjects/1.0.0
rr_sub1 = pd.read_csv('https://physionet.org/files/rr-interval-healthy-subjects/1.0.0/007.txt?download',
                      header=None, names=['sub7'])
rr_sub2 = pd.read_csv('https://physionet.org/files/rr-interval-healthy-subjects/1.0.0/009.txt?download',
                      header=None, names=['sub9'])

# Left-join
rr = rr_sub1.merge(rr_sub2, left_index=True, right_index=True)

# Having multiple plots with equal widths / heights
rr_label = 'RR interval (ms)'
cnt_label = 'Count'
title_fontsize = 12
fig2, axes = plt.subplots(2, 4, figsize=(12, 6))
# Typical histogram
axes[0, 0].hist(rr['sub7'], edgecolor='k', color='r', alpha=0.6, label='sub7')
axes[0, 0].set_title('axes[0, 0]: Plain histogram', fontsize=title_fontsize)
axes[0, 0].set_xlabel(rr_label)
axes[0, 0].set_ylabel(cnt_label)
axes[0, 0].legend()   # this will display the label of `axes[0, 0]`: 'sub7'
# Step
axes[0, 1].hist(rr['sub7'], edgecolor='b', histtype='step', density=True, label='sub7')
axes[0, 1].set_title('axes[0, 1]: Step', fontsize=title_fontsize)
axes[0, 1].set_xlabel(rr_label)
axes[0, 1].set_ylabel("Density")
axes[0, 1].legend()
# Cumulative density
axes[0, 2].hist(rr['sub7'], cumulative=1, histtype='step', density=True, label='sub7')
axes[0, 2].set_title('axes[0, 2]: Cumulative', fontsize=title_fontsize)
axes[0, 2].set_xlabel(rr_label)
axes[0, 2].set_ylabel('Cumulative density')
axes[0, 2].legend()
# Customized bin size
# If you provide a range or a list, it will note numbers as the boundaries of bins.
# If you provide an integer, it will be the number of bins.
axes[0, 3].hist(rr['sub7'], bins=np.arange(500, 1200, 100), fill=False, label='sub7')
axes[0, 3].set_title('axes[0, 3]: Custom bins', fontsize=title_fontsize)
axes[0, 3].set_xlabel('bin dx = 100 ms')
axes[0, 3].set_ylabel(cnt_label)
axes[0, 3].legend()
# Stacked bar
axes[1, 0].hist(rr, edgecolor='k', histtype='barstacked', label=rr.columns)
axes[1, 0].set_title('axes[1, 0]: Stacked bar', fontsize=title_fontsize)
axes[1, 0].set_xlabel(rr_label)
axes[1, 0].set_ylabel(cnt_label)
axes[1, 0].legend()
# Stacked steps
axes[1, 1].hist(rr, histtype='step', stacked=True, label=rr.columns)
axes[1, 1].set_title('axes[1, 1]: Stacked step', fontsize=title_fontsize)
axes[1, 1].set_xlabel(rr_label)
axes[1, 1].set_ylabel(cnt_label)
axes[1, 1].legend()
# Side-by-side
axes[1, 2].hist(rr, fill=False, edgecolor=['C0', 'C1'], label=rr.columns)
axes[1, 2].set_title('axes[1, 2]: Side-by-side', fontsize=title_fontsize)
axes[1, 2].set_xlabel(rr_label)
axes[1, 2].set_ylabel(cnt_label)
axes[1, 2].legend()
# 2D histogram
axes[1, 3].hist2d(rr['sub7'], rr['sub9'], bins=20)
axes[1, 3].set_title('axes[1, 3]: 2D histogram', fontsize=title_fontsize)
axes[1, 3].set_xlabel('sub7 interval (ms)')
axes[1, 3].set_ylabel('sub9 interval (ms)')

# Editing 'figure' property.
fig2.suptitle('HISTOGRAMS!', fontsize=16)
plt.tight_layout()

"""## Customized Layouts
<a id='customization'></a>

*When to use GridSpec*: When the story requires unequal column widths or a full-width panel.
"""

fig3 = plt.figure(layout='constrained', figsize=(9, 6))

# This is the layout of the figure we want
# +-------------------------+----------+
# |                         |          |
# |         Ax1             |    Ax2   |   ratio: 2:1
# |                         |          |
# +-------------------------+----------+
# |                                    |
# |               A3                   |   entire bottom row
# |                                    |
# +------------------------------------+

gs = GridSpec(2, 3, figure=fig3)
ax1 = fig3.add_subplot(gs[0, :-1])
ax2 = fig3.add_subplot(gs[0, -1])
ax3 = fig3.add_subplot(gs[1, :])

ax1.plot(rr['sub9'])
ax1.set_title('sub9: Reduced view', fontsize=16)
ax1.set_xlabel('Sample number')
ax1.set_ylabel('Interval (ms)')
ax1.set_xlim(0, 10000)

# Why 'cividis'? Better perceptual uniformity and colorblind-friendliness.
ax2.hexbin(rr['sub7'], rr['sub9'], gridsize=20, cmap='cividis')
ax2.set_title('Hexbin', fontsize=16)
ax2.set_xlabel('sub7 interval')
ax2.set_ylabel('sub9 interval')

ax3.plot(rr['sub7'])
ax3.set_title('sub7: Full view', fontsize=16)
ax3.set_xlabel('Sample number')
ax3.set_ylabel('Interval (ms)')

"""## Common Pitfalls & Tips
<a id='common-pitfalls--tips'></a>
- **Axes labels** - *Why* : standalone figures travel far. *Fix* : always include units using `plt.xlabel()` and `plt.ylabel()`.
- **Legends** - *Why* : avoid redundancy; if a single line, encode identity in the title. Otherwise, use `label=...` and `plt.legend()`.
- **Clipping** - *Why* : busy labels get cut. *Fix* : `tight_layout()` or `constrained_layout=True` (`layout='constrained'` is also accepted).
- **Axis specific design** - Start with `fig, ax = plt.subplots()` and call methods on `ax` for cleaner code.
- **Many subplots** - For many subplots, prefer `fig, axes = plt.subplots(nrows=..., ncols=...)` and loop.
- **Saving** - Why : reviewers often print. *Fix* : `fig.savefig('name.png', dpi=300, bbox_inches='tight')`, prefer PNG for raster, SVG/PDF for vector.
"""