# -*- coding: utf-8 -*-
"""Week5_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/137-SbeK6iOCz-n-zkqhCKr8lt0y1RxfA

# Week 5 Assignment — Control Flow & Functions

**Instructions**
- Fill in the code cells below.
- Prefer clear, readable solutions.
- Unless asked, do *not* use external packages.
- You may run cells multiple times.

**Covers**: `if/elif/else`, list comprehension with conditions, `for`/`while`, `break`/`continue`, `enumerate`/`zip`, functions (parameters, returns).

## Task 1 — If/Else + Function
Write a function `bmi_category(height, weight)` that computes BMI (kg/m²):

- BMI = `weight / (height/100)**2`
- Return:
  - `'underweight'` if BMI < 18.5
  - `'normal'` if BMI < 25
  - `'overweight'` otherwise

Test with at least 3 examples (print the input, BMI (rounded), and the category).
"""

# Your code for Task 1
def bmi_category(height, weight):
    ...  # TODO: implement

# Examples:
examples = [(170, 55), (165, 70), (180, 90)]
for h, w in examples:
    # TODO: compute bmi and category, then print nicely
    pass

"""## Task 2 — List Comprehension with Condition

Expected: odds from 1...20 -> [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

From numbers 1–20:
- Create a list of only odd numbers via list comprehension.
- Create a list labeling each number `'even'` or `'odd'` via list comprehension (inline `if/else`).
"""

# Your code for Task 2
nums = list(range(1, 21))
odds = ...  # TODO
labels = ...  # TODO: 'even' if n % 2 == 0 else 'odd'
print(odds)
print(labels)

"""## Task 3 — Loops: for, enumerate, zip
Given:
```python
subjects = ["sub01","sub02","sub03"]
ages = [5, 7, 6]
```
- Use `enumerate` to print the index and subject.
- Use `zip` to print `subXX is N years old` for each pair.
"""

# Your code for Task 3
subjects = ["sub01","sub02","sub03"]
ages = [5, 7, 6]

# enumerate
for ... in enumerate(subjects):
    pass    # TODO: erase 'pass' and print the index and subject label

# zip
for ... in zip(subjects, ages):
    pass    # TODO: erase 'pass' and print 'subXX is N years old` where 'XX' and 'N' iterate.

"""## Task 4 — break & continue
Print numbers 1–10, but:
- Skip even numbers using `continue`.
- Stop completely once you hit `7` using `break`.
"""

# Your code for Task 4
# Expected printed sequence is 1, 3, 5 (7 should not print)
for n in range(1, 11):
    ...  # TODO

"""## Task 5 — While Loop
Find the first number **greater than 100** that is divisible by **both 7 and 9**. Print the result.
"""

# Your code for Task 5
# Hint. LCM(7, 9) = 63, so you're effectively searching for a multiple of 63.
# Please use `if all(iterables)` if you can.
# ex. `if all((n is divisible by 7), (n is divisible by 9)): print(...)`
n = 101
while True:
    ...  # TODO

"""## Task 6 — Functions (multiple returns)
Write a function `word_stats(words)` that returns two values:
1) total word count, 2) longest word length.

Example: `word_stats(["hi","hello","data"])` → `(3, 5)`.

Hint. Consider `list(map(len, words))` as a concise approach. `map` is a function that applies a function to iterables.

```
words = ["hi", "hello", "data"]
# This will return [len("hi"), len("hello"), len("data")]
# which is [2, 5, 4]
list(map(len, words))
```

Then you can use `max` to return the longest word length.
"""

# Your code for Task 6
def word_stats(words):
    ...  # TODO

print(word_stats(["hi","hello","data"]))

"""## (Optional) Task 7 — Functional Style
Rewrite Task 2 using `map` and `lambda`. Compare with your comprehension solution: which is clearer?

*Note*. `lambda` function in Python is a quick way to define simple function.

So instead of this:
```
def square_num(x):
    return x**2

list(map(square_num, [1, 2, 3, 4]))
```

you can directly define the function `square_num` using `lambda`:
```
list(map(lambda x: x**2, [1, 2, 3, 4]))
```
"""

# Your code for Task 7 (optional)
nums = list(range(1, 21))
squares_via_map = ...  # e.g., list(map(lambda x: x**2, nums))
labels_via_map = ...   # e.g., list(map(lambda n: 'even' if n%2==0 else 'odd', nums))
print(squares_via_map[:5], '...')
print(labels_via_map)

"""---
### Submission checklist
- [ ] All tasks run without errors
- [ ] Your functions return the correct values
- [ ] Printed outputs look reasonable

Good luck!

"""