#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 11 10:27:02 2025

@author: trishakesar
"""

## Trisha Kesar Week 2 Homework 

import pandas as pd

# Read data using an url

# source: Hongn, Bosch, Prado, and Bonomini (2025).
# Wearable Device Dataset from Induced Stress and Structured Exercise Sessions

url = "https://physionet.org/files/wearable-device-dataset/1.0.1/Wearable_Dataset/AEROBIC/S08/ACC.csv?download"

# Read the csv file using the url
data = pd.read_csv(url)



# Task 1. Check the structure of the data using `.head()` and `.info()`.
data.head()
data.info()
print (data.tail())

#         How many rows and columns are there? 
### Answer - Based on the display from data.info there are 3 columns, 64950 rows
#         What's the data type of each column?
### Answer - The data types are float64, which is a 64-bit floating-point number 
####        used to store numeric values with decimals.
#         What are the names of the columns?
###  Answer- The colmn names are "2013-02-25 18:00:59", "2013-02-25 18:00:59.1"
###             "2013-02-25 18:00:59.2"
#         Do you see why the names are such?
### Answer - I think these are date, followed by time stamp, then data sample



# Task 2. Print the names of the columns.
### Answer - Done with print(data.columns)
print(data.columns)


# Task 3. Please change the column names to 'ACC_X', 'ACC_Y', and 'ACC_Z'.
#         (Hint. Use `data.rename(...)` - check out the slides!)
#         Don't forget to add `inplace=True`
data.rename(columns={'2013-02-25 18:00:59':'ACC_X'}, inplace=True)
data.rename(columns={'2013-02-25 18:00:59.1':'ACC_Y'}, inplace=True)
data.rename(columns={'2013-02-25 18:00:59.2':'ACC_Z'}, inplace=True)


# Task 4. Please display the first 10 rows and 3 columns using `.iloc[]`
data.iloc[:10,:]



# Task 5. Please display the values of 'ACC_X' and 'ACC_Y' where 'ACC_X' is greater than 30
#         (Hint. Use `data.loc[]`)

data.loc[data["ACC_X"] > 30, ['ACC_X', 'ACC_Y']]

#data.iloc[data["ACC_X"]>30, :10, :]


# Task 6. Run `data.describe()`.

data.describe()


# Task 7. Get the mean, std, min, and max of each colum using different methods.
#         (Hint. `data.mean()`)

#data.ACC_X(mean)
#data.mean(ACC_X)
mean_ACC_X = data["ACC_X"].mean()
print (mean_ACC_X)

mean_ACC_Y = data["ACC_Y"].mean()
print (mean_ACC_Y)

mean_ACC_Z = data["ACC_Z"].mean()
print (mean_ACC_Z)

stdev_ACC_X = data["ACC_X"].std()
print (stdev_ACC_X)

stdev_ACC_Y = data["ACC_Y"].std()
print (stdev_ACC_Y)

stdev_ACC_Z = data["ACC_Z"].std()
print (stdev_ACC_Z)

# Second method to do the same thing with shorter code... 
mean_ACC_all = data[["ACC_X", "ACC_Y", "ACC_Z"]].mean()
print (mean_ACC_all)

stdev_ACC_all = data[["ACC_X", "ACC_Y", "ACC_Z"]].std()
print (mean_ACC_all)

max_ACC_all = data[["ACC_X", "ACC_Y", "ACC_Z"]].max()
print (max_ACC_all)

min_ACC_all = data[["ACC_X", "ACC_Y", "ACC_Z"]].min()
print (min_ACC_all)

# Third method to do the same thing - 
mean_ACC_all_2 = data.mean()
print (mean_ACC_all_2)

# I tried to add the mean as a new last row in the original data table 
data.loc["Mean"] = mean_ACC_all


##%%%
#### Extra - read slightly more complicated file and plot data

# source: Gonzalez, Zelechowska, and Jensenius (2012)
# MICRO Motion capture data from groups of participants standing still to auditory stimuli

# Please download the file first and open it:
# https://physionet.org/content/music-motion-2012/1.0/mocap_data/nmB.tsv

# %%
mocap_tsv = 'https://physionet.org/files/music-motion-2012/1.0/mocap_data/nmB.tsv?download'

# %%
# Task E1. How many rows would you skip?
# (Hint. Distinguish metadata from data!)
df_tsv = pd.read_csv(mocap_tsv, sep="\t")

headers = df_tsv.columns
print(headers)

       #nskip = ...

# %%
# Task E2. Read dataset using `nskip` you defined earlier
# This is a .tsv file (Tab Separated Version). Therefore, you need to provide
# `sep` argument.

# This is little large, so it may take some time to read.
mocap = pd.read_csv(..., sep=..., skiprows=..., engine='c')

# Here I summarized metadata. This may help you determine the answer for Task E1.
metadata = {'n_frames': 35601,
            'n_cameras': 9,
            'n_markers': 11,
            'frequency': 100,
            'n_analog': 0,
            'analog_frequency': 0,
            'description': '',
            'timestamp': '2012-03-08, 10:57:11',
            'timestamp_utc': 433180.87151356,
            'data_included': '3D',
            'marker_names': ['static', 's1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's11', 's12']}

# %%
# Task E3. Let's take a subset of this data by taking the first 100 rows.
# Use `.iloc[]` to get the first 100 rows and save it to a variable, 'subset'
subset = ...

# The first value of the returned tuple should be 100.
# If not, change the slice above.
subset.shape

# %%
# Task E4. Let's draw line plots using columns: 's2 X' & 's3 X'
subset.plot.line(...)

# %%
# Task E5. Draw a scatterplot of 'static Y' vs. 'static Z' column
# Increase `s` from 10 to a 20. What does change?
subset.plot.scatter(x=..., y=..., edgecolor='C0', color='None', s=10)

# %%
# Task E6. Plot a histogram of 's3 Y' column
subset.plot.hist(column=..., facecolor='None', edgecolor='k')



