# -*- coding: utf-8 -*-
"""week4_assginment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13LFsR_O-Qln-IKpPEW14PSrKpv1Yc_II
"""
# %% import packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec

# %% loading data
data = pd.read_csv('https://physionet.org/files/gaitpdb/1.0.0/GaCo01_01.txt?download',
                   sep='\t', header=None,
                   names=['Time',
                          *[''.join(('LS', str(p))) for p in range(8)],
                          *[''.join(('RS', str(q))) for q in range(8)],
                          'Total_LS', 'Total_RS'])

# %% Preparing the dataset
ts = data['LS0'].to_numpy()
t = data['Time'].to_numpy()

# %% Moving average
k = 101
ma = np.convolve(ts, np.ones(k)/k, mode='same')

# %% Normalization (min-max)
ts_min, ts_max = ts.min(), ts.max()
ts_norm = (ts - ts_min) / (ts_max - ts_min)

# %% Task 1. Please draw a line plot
# 1a. Create a figure and an axis using `plt.subplots()`. Make the figure size 12 x 4 inches.
fig, ax = plt.subplots(1, 1, figsize=(12, 4))
# 1b. Plot 'ts' against 't'. Set the 'alpha' value to 0.3
ax.plot(t, ts, alpha=0.3)
# 1c. Plot 'ma' against 't'. Set the linewidth to 2 by inserting 'lw=2'.
#     Also add a label: 'Window size: k' where k is the variable defined above.
#     (Hint. Check how f-string was used under 'Modifying axis properties' in Plotting_in_Python.ipynb)
ax.plot(t, ma, lw=2, label=f'Window size: {k}')
ax.plot(t, ts_norm, ls='--', label='normalized (rescaled)')
# 1d. Set X-axis label: 'Time (s)'
ax.set_xlabel('Time (s)')
# 1e. Set Y-axis label: 'Force (N)'
ax.set_ylabel('Force (N)')
# 1f. Set the title: 'Time series with moving average & normaliztion'
ax.set_title('Time series with moving average & normalization')
# 1g. Display labels by running the line: `ax.legend()`
ax.legend()

# We will emphasize certain window (30-40s)
ax.axvspan(30, 40, color='C1', alpha=0.2)
# 1h. Add text: 'highlight'. Left position is 30.5, bottom position is `ts.max()*0.95`.
#     Set the fontsize to 10
ax.text(30.5, ts.max()*0.95, 'highlight', size=10)

# This is how you save a figure.
fig.savefig('Time_series.png', dpi=300)

# %% Task 2. Please draw a scatterplot
# 2a. Make a 12 x 6 inches figure. Prepare two axes, each occupying one column.
fig2, ax2 = plt.subplots(1, 2, figsize=(12, 6))
#####################
# Left: scatterplot #
#####################
# 2b. We will only use the first 100 points from each timeseries.
#     The first timeseries is data['LS0']. The second one is data['LS1']
#     Use `.iloc[0:100]` to trim the data you will visualize
#     Set the marker to '+' and 'alpha' to 0.6. Set 'color' to 'g'(green).
sub = data.iloc[0:100, :]
ax2[0].scatter(sub['LS0'], sub['LS1'], marker='+', alpha=0.6, color='g')
ax2[0].axis('equal')
# We will add lines indicating medians of the two timeseries
# 2c. Please get the median of the first 100 samples of data['LS0'] and data['LS1']
#     Save them to variables 'ls0_median' and 'ls1_median', respectively.
#     You can use `.median()`
ls0_median = sub['LS0'].median()
ls1_median = sub['LS1'].median()
# 2d. Use `.axhline()` and `.axvline()` to mark medians.
#     Do make use of the two variables you created above.
#     (Hint. Check how `.axhline()` is used under 'Modifying axis properties' in Plotting_in_Python.ipynb)
ax2[0].axhline(y=ls1_median, xmin=0, xmax=1, color='r', ls='--')
ax2[0].axvline(x=ls0_median, ymin=0, ymax=1, color='r', ls=':')
# Add texts: medians
ax2[0].text(30, ls1_median+10, f"Position 2 median:\n{ls1_median:.2f}N",
            color='C1')
ax2[0].text(ls0_median+10, 200, f"Position 1 median:\n{ls0_median:.2f}N",
            color='C0')
# 2e. Set X-axis label: 'Left foot position 1 (N)'
ax2[0].set_xlabel('Left foot position 1 (N)', color='C0', weight='bold')
# 2f. Set Y-axis label: 'Left foot position 2 (N)'
ax2[0].set_ylabel('Left foot position 2 (N)', color='C1', weight='bold')
#####################
# Right: Histogram  #
#####################
# 2g. Draw a stacked bar histogram on the right pane.
#     You need to provide the first 100 samples of 'LS0' and 'LS1' of 'data'.
ax2[1].hist(sub.loc[:, ['LS0', 'LS1']], histtype='barstacked',
            label=['Position 1', 'Position 2'],
            edgecolor='k')
ax2[1].set_xlabel("Force (N)")
ax2[1].set_ylabel("Count")
# 2h. Display legend
ax2[1].legend()

# 2i. Save the figure as 'Two_plots.png'. Set dpi=300.
fig2.savefig('Two_plots.png', dpi=300)

# %% Task 3.

# This is the layout of the figure we want
# +------------------------------------+
# |                                    |
# |                 ax3a               |   entire top row
# |                                    |
# +--------+--------+------------------+
# |        |        |                  |
# |  ax3b  |  ax3c  |       ax3d       |   1:1:2
# |        |        |                  |
# +------------------------------------+

# We will be using RR interval data.
rr_sub1 = pd.read_csv('https://physionet.org/files/rr-interval-healthy-subjects/1.0.0/007.txt?download',
                      header=None, names=['sub7'])
rr_sub2 = pd.read_csv('https://physionet.org/files/rr-interval-healthy-subjects/1.0.0/009.txt?download',
                      header=None, names=['sub9'])
rr = rr_sub1.merge(rr_sub2, left_index=True, right_index=True)

fig3 = plt.figure(layout='constrained', figsize=(10, 6))
# 3a. Set the grids
# 3a.1. Provide nrow and ncol to `GridSpec`. Please note that the width ratio of
#       the three axes at the bottom row are 1:1:2.
gs = GridSpec(2, 4, figure=fig3)
# 3a.2. Use correct slices. Each input to the following four rows
#       needs to be `gs[row_number, column_range]
ax3a = fig3.add_subplot(gs[0, :])       # Top row, covering all colums
ax3b = fig3.add_subplot(gs[1, :-3])       # Bottom row, covering the first column
ax3c = fig3.add_subplot(gs[1, 1:-2])       # Bottom row, covering the second column
ax3d = fig3.add_subplot(gs[1, 2:])       # Bottom row, covering the remaining columns

# 3b. Secondary y axis on ax3b
ts1 = rr['sub7'].iloc[0:200].to_numpy()
ts2 = rr['sub7'].iloc[10000:10200].to_numpy()
ts_diff = ts2 - ts1
ax3a2 = ax3a.twinx()
# 3b.1. Plot the raw data: rr['sub7'] & rr['sub9']
#       Label each as 'First 200 samples' and '50th 200 samples'
#       Set color as 'C1' and 'C2', respectively.
#       Set alpha to 0.5
ax3a.plot(ts1, label='First 200 samples', color='C1', alpha=0.5)
ax3a.plot(ts2, label='50th 200 samples', color='C2', alpha=0.5)
# 3b.2. Set the title: 'sub 7: Window difference'
ax3a.set_title('sub 7: Window difference')
# 3b.3. Set X axis label: 'Sample number' and Y axis label: 'RR interval (ms)'
ax3a.set_xlabel('Sample number')
ax3a.set_ylabel('RR interval (ms)')
# Plot the difference of the two timeseries along the secondary axis: ax3b2
# Use additional arguments: `color='C0', label='Difference'`
ax3a2.plot(ts_diff, color='C0', label='Difference')
ax3a2.set_ylabel("Interval difference (ms)")
# legends
lns = ax3a.get_lines() + ax3a2.get_lines()
labels = [l.get_label() for l in lns]
# Display legend on the upper right
ax3a.legend(lns, labels, loc='upper right')

# 3c. Histogram with custom bin labels
# 3c.1. Make bins to range from 500 to 1300, with dx=50 (Hint: use `np.arange`)
bins = range(500, 1300, 50)
# 3c.2. Draw a histogram of rr['sub7']. Provide `bins` and set alpha to 0.7 +
#       edgecolor to 'k' (black).
ax3b.hist(rr['sub7'], bins=bins, alpha=0.7, edgecolor='k')
# m: mean of the data; s: standard deviation of the data
m, s = rr['sub7'].mean(), rr['sub7'].std()
# 3c.3. Draw a vertical line showing the mean of the data.
#       Use `.axvline`. Set color to 'C1', linewidth (lw) to 2,
#       and label to f'mean={m:.1f}'
ax3b.axvline(x=m, color='C1', lw=2, label=f'mean={m:.1f}')
ax3b.axvspan(m-s, m+s, color='C1', alpha=0.15, label=f'+/- 1SD={s:.1f}')
# Add:
# - a title('sub 7')
# - X/Y axis labels('RR interval(ms)' & 'Count')
# - legend
ax3b.set_title('sub 7')
ax3b.set_xlabel('RR interval (ms)')
ax3b.set_ylabel('Count')
ax3b.legend()

# 3d. Histograms, overlaid
# 3d.1. Draw histograms, similar to 'Side-by-side' example of 'Plotting_in_Python.ipynb'
#       additional parameters: edgecolor='k', alpha=0.5, bins=25, label=??
ax3c.hist(rr, edgecolor='k', alpha=0.5, bins=25, label=rr.columns)
# 3d.2. Add X/Y axis labels and legend, same as 3c.
ax3c.set_xlabel('RR interval (ms)')
ax3c.set_ylabel('Count')
ax3c.legend()

# 3e. 2D histogram
# 3e.1. Use `.hist2d`. You should plot rr['sub7'] and rr['sub9'].
#       Use cmap='magma' and bins=35.
ax3d.hist2d(rr['sub7'], rr['sub9'], cmap='magma', bins=35)
# 3e.2. Set X/Y axis labels:
#       - 'sub 7, RR interval (ms)'
#       - 'sub 9, RR interval (ms)'
ax3d.set_xlabel('sub 7, RR interval (ms)')
ax3d.set_ylabel('sub 9, RR interval (ms)')
# 3f. Save the figure as 'Custom_layout.png'; use dpi=300
fig3.savefig('Custom_layout.png', dpi=300)

