# -*- coding: utf-8 -*-
"""Week3_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aqh6pPcYRE3rj8TamWBbI_-34Ar4xcFZ

# Reproduce the dataframes in Week3 learning material + etc.
"""

# %% Import package & data reading preparation
import pandas as pd

github_url = 'https://raw.githubusercontent.com/ohspc89/reprorehab2025/students/contents/week3'
suffix = '.csv'
# Do you recognize `.join()` and a list comprehension?
fnames = ['/'.join((github_url, f'sub{str(x+1).zfill(2)}'+suffix)) for x in range(4)]
# Give column names
column_names = ['Measure_A', 'Measure_B']

# %% Save all dataframes in a list
dfs = []
# Loop over file names
for fname in fnames:
  # `.append()` is a method that attaches an input at the end of a list
  dfs.append(pd.read_csv(fname, header=None, names=column_names))

"""**Task 1**. You will add new columns: 'id' & 'time'

- 'id' column of the first dataframe (`dfs[0]`) will have 'sub1' as its value. Repeat as many times as you need.
- 'id' column of the second dataframe (`dfs[1]`) will have 'sub2' as its value. Similar will be true for the third and the fourth dataframe in `dfs`.
- 'time' column will have three values: 'pre', 'test', 'post'. You will make it as a categorical variable (hint. `pandas.Categorical()`). The levels will be **pre -> test -> post**.
"""

# %% Complete this block
for i, df in enumerate(dfs):
  df['id'] = f'sub{i+1}'    # if i is 0, this should be repeated accounts of 'sub1'
  df['time'] = pd.Categorical(['pre', 'test', 'post'],
                              categories=['pre', 'test', 'post'],
                              ordered=True)
  df = df.iloc[:, [2, 3, 0, 1]]
  dfs[i] = df

"""**Task 2**. Then you will concatenate the elements of `dfs` using `pandas.concat()`."""

# %% Complete this code block
with_id = pd.concat(dfs, ignore_index=True)

"""**Task 3**. Use `pandas.DataFrame.melt()` to prepare a *long* dataframe. Just set `id_vars` and `value_vars` and leave the rest to default options."""

# %%
# Use `pd.DataFrame.melt()` to prepare a long format
#   id_vars : scalar, tuple, list, or ndarray, optional
#       Column(s) to use as identifier variables.
#   value_vars : scalar, tuple, list, or ndarray, optional
#       Column(s) to unpivot. If not specified, uses all columns that
#       are not set as id_vars.
#   var_name : scalar, default None
#       Name to use for the 'variable' column. If None it uses
#       frame.columns.name or 'variable'.
#   value_name : scalar, default 'value'
#       Name to use for the 'value' column, can't be an existing column label.
long_form = with_id.melt(id_vars=['id', 'time'],
                         value_vars=['Measure_A', 'Measure_B'])

"""**Task 4**. Use `pandas.DataFrame.pivot()` to prepare a *wide* dataframe."""

# %% Use `pandas.DataFrame.pivot()`
wide_form = long_form.pivot(index='id', columns=['time', 'variable'],
                            values='value')

# %% Copying from the learning materials - run it please!
wide_form.columns = ['-'.join((x[1], x[0])) for x in wide_form.columns]
# If you skip this command, 'id' will stay as index.
wide_form = wide_form.reset_index()


"""Run the code block below to prepare `back_to_long`."""

back_to_long = wide_form.melt(id_vars='id')
# Use `.sort_values(by='id')` to sort by the column: id
# Use `.reset_index(drop=True)` to reset the row numbers
back_to_long = back_to_long.sort_values(by='id').reset_index(drop=True)

"""**Task 5**. Modify one column and make a new column in **back_to_long**: **variable** and **time**. Use `.str.split()` to split strings of **variable** column and use `expand=True` to populate new columns."""

# %% Complete the code
back_to_long[['variable', 'time']] = back_to_long['variable'].str.split('-', expand=True)

"""**Task 6**. Make **time** column a categorical one. Set the level identical to what's described in task 1."""

# %% Complete the code
back_to_long['time'] = pd.Categorical(back_to_long['time'],
                                      categories=['pre', 'test', 'post'],
                                      ordered=True)

"""**Task 7**. Let's sort values so that you will get a dataframe like this:
```
     id | time | variable  | value |
--------+------+-----------+-------|
0  sub1 | pre  | Meausre_A | 3.2   |
1  sub1 | test | Measure_A | 7.8   |
2  sub1 | post | Measure_A | 5.1   |
3  sub2 | pre  | Measure_A | 9.8   |
4  sub2 | test | Measure_A | 1.2   |
5  sub2 | post | Measure_A | 7.7   |
   ...  | ...  |    ...    | ...   |
21 sub4 | pre  | Measure_B | 5.5   |
22 sub4 | test | Measure_B | 7.1   |
23 sub4 | post | Measure_B | 6.8   |
-----------------------------------+
```

You only need to provide the value for `by` in `.sort_values()`.
"""

# %% Complete the code
back_to_long.sort_values(by=['variable', 'id', 'time']).reset_index(drop=True).iloc[:, [0, 3, 1, 2]]

"""Task 8. Using **wide_form**, complete the following tasks"""

# %%
# 8a. Only take columns whose names end with 'pre'. Use `.str.endswith()`.

# Expected output:

# Measure_A-pre | Measure_B-pre |
# --------------+---------------|
#           3.2 |           2.8 |
#           9.8 |           3.3 |
#           6.2 |           2.7 |
#           4.4 |           5.5 |
# ------------------------------+
wide_form.loc[:, wide_form.columns.str.endswith('pre')]

# %%
# 8b. Check "Measure_A' values of 'sub1' at all time points. Use `.str.startswith()`.

# Expected output:

# Measure_A-pre | Measure_A-test | Measure_A-post |
# --------------+----------------+----------------|
#           3.2 |            7.8 |            5.1 |
wide_form.loc[wide_form['id'].str.match('sub1'), wide_form.columns.str.startswith('Measure_A')]

"""Task 9. Using **back_to_long**, complete the following tasks."""

# %%
# 9a. Filter out rows whose 'time' is 'pre' and whose 'variable' ends with 'B'.
# Use `.str.match()` and `.str.endswith()`.

# Expected output

#     id | time | variable  | value |
# -------+------+-----------+-------|
#   sub1 | pre  | Meausre_B | 2.8   |
#   sub2 | pre  | Measure_B | 3.3   |
#   sub3 | pre  | Measure_B | 2.7   |
#   sub4 | pre  | Measure_B | 5.5   |
# ----------------------------------+

long_form.loc[(long_form.time.str.match('pre')) & long_form.variable.str.endswith('B')]

# %%
# 9b. Take rows whose 'value' is less than 4.0
long_form.loc[long_form.value < 4.0, :]
