# -*- coding: utf-8 -*-
"""Week2_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-d2-PZ_9SbxWG44KY-I1wez1xIKsB93
"""

# %% import package
import pandas as pd

# Read data using an url

# source: Hongn, Bosch, Prado, and Bonomini (2025).
# Wearable Device Dataset from Induced Stress and Structured Exercise Sessions

# %% Read dataset
url = "https://physionet.org/files/wearable-device-dataset/1.0.1/Wearable_Dataset/AEROBIC/S08/ACC.csv?download"

# Read the csv file using the url
data = pd.read_csv(url)

# %%
# Task 1. Check the structure of the data using `.head()` and `.info()`.
#         How many rows and columns are there? What's the data type of each column?
#         What are the names of the columns? Do you see why the names are such?

data.head()
data.info()


# %%
# Task 2. Print the names of the columns.
data.columns

# %%
# Task 3. Please change the column names to 'ACC_X', 'ACC_Y', and 'ACC_Z'.
#         (Hint. Use `data.rename(...)` - check out the slides!)
#         Don't forget to add `inplace=True`
data.rename(columns={x:y for x,y in zip(data.columns, ['ACC_X','ACC_Y','ACC_Z'])}, inplace=True)


# %%
# Task 4. Please display the first 10 rows and 3 columns using `.iloc[]`
data.iloc[:10, :3]

# %%
# Task 5. Please display the values of 'ACC_X' and 'ACC_Y' where 'ACC_X' is greater than 30
#         (Hint. Use `data.loc[]`)
data.loc[data['ACC_X']>30,['ACC_X','ACC_Y']]

# %%
# Task 6. Run `data.describe()`.

data.describe()


# %%
# Task 7. Get the mean, std, min, and max of each colum using different methods.
#         (Hint. `data.mean()`)
data.mean()
data.std()
data.min()
data.max()

# Extra - read slightly more complicated file and plot data

# source: Gonzalez, Zelechowska, and Jensenius (2012)
# MICRO Motion capture data from groups of participants standing still to auditory stimuli

# Please download the file first and open it:
# https://physionet.org/content/music-motion-2012/1.0/mocap_data/nmB.tsv

# %%
mocap_tsv = 'https://physionet.org/files/music-motion-2012/1.0/mocap_data/nmB.tsv?download'


# %%
# Task E1. How many rows would you skip?
# (Hint. Distinguish metadata from data!)
nskip = 10

# %%
# Task E2. Read dataset using `nskip` you defined earlier
# This is a .tsv file (Tab Separated Version). Therefore, you need to provide
# `sep` argument.

# This is little large, so it may take some time to read.
mocap = pd.read_csv(mocap_tsv, sep='\t', skiprows=nskip, engine='c')

# Here I summarized metadata. This may help you determine the answer for Task E1.
metadata = {'n_frames': 35601,
            'n_cameras': 9,
            'n_markers': 11,
            'frequency': 100,
            'n_analog': 0,
            'analog_frequency': 0,
            'description': '',
            'timestamp': '2012-03-08, 10:57:11',
            'timestamp_utc': 433180.87151356,
            'data_included': '3D',
            'marker_names': ['static', 's1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's11', 's12']}

# %%
# Task E3. Let's take a subset of this data by taking the first 100 rows.
# Use `.iloc[]` to get the first 100 rows and save it to a variable, 'subset'
subset = mocap.iloc[:100,]

# The first value of the returned tuple should be 100.
# If not, change the slice above.
subset.shape

# %%
# Task E4. Let's draw line plots using columns: 's2 X' & 's3 X'
subset.plot.line(x='s1 X', y='s3 X')


# %%
# Task E5. Draw a scatterplot of 'static Y' vs. 'static Z' column
# Increase `s` from 10 to a 20. What does change?
subset.plot.scatter(x='static Y', y='static Z', edgecolor='C0', color='None', s=10)
subset.plot.scatter(x='static Y', y='static Z', edgecolor='C0', color='None', s=20)
# it made the points on the plot bigger

# %%
# Task E6. Plot a histogram of 's3 Y' column
subset.plot.hist(column='s3 Y', facecolor='None', edgecolor='k')
