# -*- coding: utf-8 -*-
"""Data_wrangling_pandas_part2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QC2NOxAtJreVjYADP_mynIzzGC3J7JCo

# Manipulating tabular data with Pandas II: reorganize & reshape

## Agenda

1. Filtering rows with conditions
2. Sorting data
3. Applying functions to columns
4. Merging & concatenating DataFrames
5. Reshaping (Long <-> Wide)

### Why This Week Matters
In research, data almost never arrive in the perfect format. They come as multiple CSVs, different layouts, or wide spreadsheets that can't be easily analyzed.

This week you'll learn how to:
- Filter and sort tables
- Create new columns and transform data
- Merge, concatenate, and reshape tables

so that by the end, you'll be able to turn *any* messy data into a clean, analysis-ready dataset.
"""

import pandas as pd

"""## Filtering rows with conditions

#### Concept
Filtering means selecting only the rows that meet specific criteria.

For example: "Show only the participants older than 50" or "Only rows where `Group == 'Control'`."

#### Goal
Learn how to use `.loc[]` to select rows based on conditions.

- **syntax**: `pandas.DataFrame.loc[condition, cols]`
- How to chain multiple conditions?: use `&` symbol
- Using `isin` to check if a string / number belongs to a list / set
"""

# First ladies
first_ladies = pd.read_csv(
    'https://raw.githubusercontent.com/ohspc89/reprorehab2025/students/contents/week3/first_ladies.csv')

# Make it a habit of check how the read file looks.
first_ladies.head()

"""We discussed last week that `.loc[(condition), columns]` is used to filter rows. If you want all columns to be selected, use `:`."""

# Example 1: simple equality check
first_ladies.loc[first_ladies["First_name"] == "Martha", :]

"""### Chaining Conditions

#### Why parentheses matter
Each condition must be in its own parentheses because `&` has lower priority than comparison operators (ex `==`, `>`, or `<`).
"""

# What was the maiden name of the wife of Mr. George W. Bush?
# pandas.DataFrame.loc[(condition 1) & (condition 2) & ..., columns]
first_ladies.loc[(first_ladies["Last_name"] == "Bush") & (first_ladies["year_start"] > 2000), "Maiden_name"]

"""###Using `isin`

Sometimes you want to check if a value *belongs* to a list. `.isin()` makes that easy. Think of it like "is that in that?"
"""

# Count how many first ladies are there with distinct first names
# `first_name_count` is a pandas.Series.
first_name_counts = first_ladies.First_name.value_counts()
# Filter: more than once!
more_than_once = first_name_counts.loc[first_name_counts > 1]
# Now, give me rows of the first ladies whose first names are not unique!
first_ladies.loc[first_ladies["First_name"].isin(more_than_once.index), :].head(8)

"""## Sorting values

#### Goal
Sorting helps you order your data logically - alphabetically, chronologically, or by magnitude.

- **syntax**: `.sort_values(by=[...], ascending=[...])`
  - Use `ascending=False` to show largest or latest values first.
- **Categorical order**
  - Why this matters? When working with experimental stages (e.g., `pre`, `test`, `post`), alphabetical order isn't meaningful. `Categorical` ordering lets you define *domain logic* instead.

`by` can be a single column or a list of columns.
"""

# Sort by the last name - see how `ascending=False` works
first_ladies.sort_values(by='Last_name', ascending=False).head(6)

# You can sort by multiple columns in order
# Sort first by 'First_name' (from Z to A), and then by 'year_start' (earlier years first)
first_ladies.sort_values(by=['First_name', 'year_start'], ascending=[False, True]).head(6)

"""Set the categorical order using `pandas.Categorical()` and you can sort by that order"""

# DataFrame
repeated_treatment = pd.DataFrame({'Subject': ['sub01'] * 5 + ['sub02'] * 5,
                                   'Timepoint': ['pre', 'post', 'treat1', 'treat2', 'treat3'] * 2,
                                   'Dose': [0.0, 0.0, 1.1, 2.2, 3.3, 2.0, 2.0, 0.8, 2.5, 3.8]})
# Timepoint is displayed in the following order:
# pre -> post -> treat1 -> treat2 -> treat3
repeated_treatment

# Set the Timepoint order to be more chronological
# (ex. pre -> treat1 -> treat2 -> treat3 -> post)
tp_level = ['pre', 'treat1', 'treat2', 'treat3', 'post']
# Set `categories` to the level you predefined, and `ordered` to True
repeated_treatment['Timepoint'] = pd.Categorical(repeated_treatment['Timepoint'],
                                                 categories=tp_level, ordered=True)

# You now see the new Timepoint order implemented
repeated_treatment.sort_values(by=['Subject','Timepoint'])

"""## Applying functions to columns

Here we'll switch from *long* to *wide* format to show how easy column-wise calculations become.

- `.assign()` creates new columns without modifying the original.
- Vectorized operations are faster than loops.
"""

# @title Transformed: `rt_v2`
rt_v2 = repeated_treatment.pivot(index='Subject', columns='Timepoint', values="Dose")
rt_v2.columns=['Dose-'+x for x in ['pre', 'treat1', 'treat2', 'treat3', 'post']]
rt_v2 = rt_v2.reset_index()

# If we have a DataFrame in wide format...
rt_v2

# ... column-wise calculation is easy.
# ex. What's the mean of pre-post dose across subjects?
(rt_v2['Dose-pre'] - rt_v2['Dose-post']).mean()

# Multiply (increase, decrease, divide by, ...)
rt_v2['Dose-treat2'] = rt_v2['Dose-treat2'] * 3
rt_v2

# Use `.assign` to create new columns easily
rt_v2 = rt_v2.assign(prepost_ratio = rt_v2["Dose-pre"]/rt_v2["Dose-post"],
                     treat_ratio = rt_v2["Dose-treat2"]/(rt_v2["Dose-treat1"] + rt_v2["Dose-treat3"]))
rt_v2

"""#### String Methods Recap
`.str` lets you treat text columns like lists of words - split, replace, capitalize, etc.
"""

# Applying the same function to string elements of a column
# Use `.str`.
# `.str.capitalize()`: Capitalization | `.str.lower()`: to lowercase | `.str.upper()`: to uppercase
rt_v2['Subject'].str.capitalize()

# `.str.replace()`: replace substring ex. 'Sub01' -> 'Subject01'
rt_v2['Subject'].str.replace('b', 'bject')

#@title Transformed (2): `rt_v2`
# Changing values for a new example
rt_v2['Subject_label'] = ['StudyA_01', 'StudyB_01']
rt_v2.drop('Subject', axis=1, inplace=True)
cols = list(rt_v2.columns)
rt_v2 = rt_v2[[cols[-1]]+cols[:-1]]
rt_v2 = rt_v2.copy()

# Subject labels are now joined with '_'. ex. 'sub_StudyA_01'
rt_v2

# `.str.split()`: splits strings.

# Split by '_': a list is generated
rt_v2['Subject_label'].str.split('_')

# If you want to keep certain elements, use `.str` one more time.
# For example, if we want the third element of the list of splitted strings:
rt_v2['Subject_label'].str.split('_').str[1]

# You can use 'expand=True' to generate new columns using splitted strings.
# The number of columns to be created should match the number of splitted strings.
rt_v2[['Study_type', 'Subject_order']] = rt_v2['Subject_label'].str.split('_', expand=True)
# Check how 'Study_type' and 'Subject_order' columns are prepared
rt_v2

"""## Merging & concatenating DataFrames

#### Concept
Merging combines datasets that share a common column (a *key*).

Think: "Add demographic info to each participant's data."

For more information, refer to this [page](https://pandas.pydata.org/docs/user_guide/merging.html)
"""

# Let's have we have the following metadata: biological sex information
metadata = pd.DataFrame({'Subject_label': ['StudyA_01', 'StudyB_01'],
                         'Sex': pd.Categorical(['F', 'M'], categories=['F', 'M'], ordered=True)})
# This dataframe has two columns: 'subject_label' and 'Sex'
metadata

"""**Key column**: `Subject_label` appears in both `rt_v2` and `metadata`. That's how pandas knows what to match."""

# Merge this with the original data using the "key" column
rt_v2.merge(metadata, on="Subject_label")

#@title Transformed (3): `rt_v2`
new_row = pd.Series(['StudyA_02', 1.2, 1.2, 6.8, 3.1, 0.9, 1.3, 1.630435, 'StudyA', '02'],
                    index=rt_v2.columns)
rt_v2 = pd.concat([rt_v2, new_row.to_frame().T]).reset_index(drop=True)

# What if your dataset has more rows than your metadata?
rt_v2

# pandas.merge defaults to "INNER JOIN", so it will only return "complete" rows.
rt_v2.merge(metadata, on='Subject_label')

# You can use "OUTER JOIN" to make ALL rows to be populated, even with NAs.
# See how 'Sex' is NaN for 'StudyA_02'.
rt_v2.merge(metadata, how='outer', on='Subject_label')

# If metadata has more rows (4 > 3)
metadata = pd.DataFrame({'Subject_label': ['StudyA_01', 'StudyB_01', 'StudyA_02', 'StudyB_02'],
                         'Sex': pd.Categorical(['F', 'M', 'M', 'F'], categories=['F', 'M'], ordered=True)})
# rows with metadata but not raw data will be populated with many more NAs.
rt_v2.merge(metadata, how='outer', on='Subject_label')

"""**Compare joins**:
- `inner`: only matching rows
- `outer`: all rows, fill missing with `NaN`

### Concatenation

#### Concept
Concatenation stacks DataFrames on top of each other - perfect for combining multiple participants or sessions.

Let's suppose you have four data files of four participants.

Each file has repeated measurements of two variables (**Measure_A**, **Measure_B**) at three time points.


ex. **sub01.csv**:

{Value of Measure_A at time 1}**,**{Value of Measure_B at time 1}\
{Value of Measure_A at time 2}**,**{Value of Measure_B at time 2}\
{Value of Measure_A at time 3}**,**{Value of Measure_B at time 3}

*Note.* values are separated by comma(,), thus csv!
"""

# @title Reading 4 files as dataframes and saving them in a list: `dfs`

# Data reading prep
github_url = 'https://raw.githubusercontent.com/ohspc89/reprorehab2025/students/contents/week3'
suffix = '.csv'
# Do you recognize `.join()` and a list comprehension?
fnames = ['/'.join((github_url, f'sub{str(x+1).zfill(2)}'+suffix)) for x in range(4)]
# Give column names
column_names = ['Measure_A', 'Measure_B']

# Save all dataframes in a list
dfs = []
# Loop over file names
for fname in fnames:
  # `.append()` is a method that attaches an input at the end of a list
  dfs.append(pd.read_csv(fname, header=None, names=column_names))

# An element of `dfs`.
dfs[0]

# `ignore_index=True` does the same trick as `.reset_index(drop=True)`.
pd.concat(dfs, axis=0, ignore_index=True)

"""## Reshaping (Long <-> Wide)"""

# @title Preparing a long dataframe

# Adding a new column: 'id' and reorder columns
for i, df in enumerate(dfs):
  df['id'] = ['sub'+str(i+1).zfill(2)]*3
  df['time'] = ['pre', 'test', 'post']
  df = df.iloc[:, [2, 3, 0, 1]]
  dfs[i] = df

# So now we can see that "id" column can help you
with_id = pd.concat(dfs, axis=0, ignore_index=True)

# Use `pd.DataFrame.melt()` to prepare a long format
#   id_vars : scalar, tuple, list, or ndarray, optional
#       Column(s) to use as identifier variables.
#   value_vars : scalar, tuple, list, or ndarray, optional
#       Column(s) to unpivot. If not specified, uses all columns that
#       are not set as id_vars.
#   var_name : scalar, default None
#       Name to use for the 'variable' column. If None it uses
#       frame.columns.name or 'variable'.
#   value_name : scalar, default 'value'
#       Name to use for the 'value' column, can't be an existing column label.
long_form = with_id.melt(id_vars=['id', 'time'], value_vars=['Measure_A', 'Measure_B'],
                         var_name='measure', value_name='value')

"""**Why we reshape**:
Statistical tests and visualization tools often need data in a *long* format, while calculation steps are easier in *wide* format.

You will learn to switch between them effortlessly.

```
+-----------+--------------+-------------------------------------+
| Operation | Converts     | Use When                            |
+-----------+--------------+-------------------------------------+
| melt()    | wide -> long | For stats/ plots                    |
+-----------+--------------+-------------------------------------+
| pivot()   | long -> wide | For summaries or paired comparisons |
+-----------+--------------+-------------------------------------+
"""

# This is long format
long_form.head()

"""*Wide* format: better for reading

Use `pandas.DataFrame.pivot()` to make a wide format dataframe.
"""

# Using `pandas.DataFrame.pivot()`
wide_form = long_form.pivot(index='id', columns=['time', 'measure'], values='value')
wide_form

"""Oh, now columns have two levels. You can also check that columns are `MultiIndex`"""

# Note that columns are not plain texts, but tuples.
# Also, 'id' is no longer a distinct column - it's used as the row index.
wide_form.columns

# You can rename the labels
wide_form.columns = ['-'.join((x[1], x[0])) for x in wide_form.columns]
# If you skip this command, 'id' will stay as index.
wide_form = wide_form.reset_index()
wide_form

# Ok, it's now Index with plain strings.
wide_form.columns

# wide format works well with `pandas.DataFrame.plot()` methods.
wide_form.plot.scatter(x='Measure_A-pre', y='Measure_A-post', color=['r', 'b', 'g', 'c'])

"""Switch back to long format using `pandas.DataFrame.melt()` or `pandas.melt()`."""

back_to_long = wide_form.melt(id_vars='id')
# Use `.sort_values(by='id')` to sort by the column: id
# Use `.reset_index(drop=True)` to reset the row numbers
back_to_long = back_to_long.sort_values(by='id').reset_index(drop=True)
back_to_long.head(8)

# Use `pd.melt()`. You just provide one more input: `pandas.DataFrame`
long_form_v2 = pd.melt(with_id, id_vars=['id', 'time'])
# Here you can check the default options used (`var_name='variable'`, `value_name='value'`)
long_form_v2.head()

# See the difference: what if you only use 'id' column as the `id_vars`?
# Rows will not be unique anmore.
long_form_v3 = pd.melt(with_id, id_vars='id', value_vars=['Measure_A', 'Measure_B'])
long_form_v3.head()

"""## Summary - What You Learned This Week
- How to filter, sort, and transform tabular data
- How to merge and stack datasets
- How to reshape between long and wide formats
- Why these transformations matter for reproducible research workflows

### Why It Matters in Rehab Research
The same tools apply whether your data come from gait sensors, motion tracking, or behavioral assessments. Once you can reshape and merge data confidently, you can handle almost any dataset used in rehabilitation studies.
"""