# -*- coding: utf-8 -*-
"""enumerate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aJ4U7m_LdWLg_1dvCtQauiKOywgqUeU0

# Week 3 Assignment - extra notes: *Loops*, `enumerate()`, and F-strings

## `enumerate`

A function in Python that adds a counter to an iterable object, allowing you to access both the index and the value of each item during iteration.

Let's first understand how does it work, and then think about when would this be useful.
"""

import numpy as np
import pandas as pd

# Let's revisit our first ladies dataframe.
first_ladies = pd.read_csv(
    'https://raw.githubusercontent.com/ohspc89/reprorehab2025/students/contents/week3/first_ladies.csv'
)

"""A `for` loop iterates over an *iterable*.

The syntax of a `for` loop goes:
```
for variable in iterable:
    (do something with the variable)
````
Every line inside a `for` loop must be indented. Spyder, Google Colab, and most editors do this automatically - but indentation *defines* the loop body in Python.


If you search "python what is iterable" on Google, AI gives you this answer: `In Python, an iterable is an object that can be looped over, meaning you can access its elements one by one.`

`range`, `list`, `dictionary`, `array (numpy)`, `Series (pandas)` are common examples of iterables.
"""

# range example

# You can check the content of `a_range` by running: `list(a_range)`.
a_range = range(1, 10)

for ar in a_range:
  print(ar)

"""`a_range` is a range, and its elements are nine integers from 1 to 9."""

list(a_range)

"""So a `for` loop will loop over the nine integers of `a_range`. A `for` loop goes through each element in order from the first to the last. In our example, the `for` loop will first access `1`, the first element of `a_range`. This value is temporarily assigned to the variable `ar`.

Inside a loop, you `print` the value of the variable `ar`. When the loop starts, you will print 1.

Once all commands outlined inside the loop (e.g., print the accessed element) are executed, the `for` loop accesses the next element of `a_range`, or 2. This behavior will repeat until the loop accesses the last element of the iterable, `a_range`.

After this loop, there will be no more element to access. That's when this loop terminates.
"""

# list example

a_list = [100, 101, 102, 103, 104, 105, 106, 107]

for al in a_list:
  print(al)

# dict example
a_dict = {'A': [2, 7], 'B': 'hello', 'C': 3.8, 'D': {'key': 'value'}}

# This will print the keys.
for ad in a_dict:
  print(ad)

print('-----')

# A more explicit version
for ad in a_dict.keys():
  print(ad)

# This will print the values.
for adv in a_dict.values():
  print(adv)

# This will print the items.
# Notice that each item in a_dict.items() is a tuple -
# a pair of key and value.
for adi in a_dict.items():
  print(adi)

# You can take keys and values separately.
# In fact, this is extremely common format.
# The cell above is not so commonly used.
for key, val in a_dict.items():
  print(key, " + ", val)

# numpy ndarray example
arr = np.array([1, 2, 3, 4, 5])

for ar in arr:
  print(ar)

print('-----')

# If an array's dimension >= 2,
# then a loop will loop over the outer-most dimension.
# For example, arr2d is a 2 by 5 matrix.
# Then the loop will loop over its 'rows'.
arr2d = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])


for ar2d in arr2d:
  print(ar2d)

print('-----')

# You won't often loop over 2D or 3D arrays
# directly in real analysis, but it's useful to
# know what happens conceptually.

# Another example of higher dimension array:
#  3 by 2 by 2 matrix.
# The loop will loop over its inner 2D matrices.
arr3d = np.array([[[1, 2],
                   [3, 4]],
                  [[5, 6],
                   [7, 8]],
                  [[9, 10],
                   [11, 12]]])
for ar3d in arr3d:
  print(ar3d)

# pandas series example
a_pd_series = first_ladies["Last_name"]

# Remember - this has the last names of the first ladies.
# Therefore, last names will be printed
for pds in a_pd_series:
  print(pds)

"""Sometimes you need both *the item and its index* while looping - for example, to print specific entries or label output. This is where `enumerate` comes handy. The syntax goes like this:

```
for index, value in enumerate(iterable, start=0):
    (do something with index, value, or both)
```
"""

for i, name in enumerate(a_pd_series):
  # I want to print names of the 6th, 13th, 14th, and 22nd first ladies
  # with a custom format.

  # Do you see why the list iterated over is
  # [5, 12, 13, 21], not [6, 13, 14, 22]?
  if i in [5, 12, 13, 21]:
    print("index_from_1 is",i+1,", and the last name is",name)

# Of course, you can do this with pandas, but printing
# custom statements using the indices and values is more tricky.
# Also, here you cannot manipulate indices.
a_pd_series[[5, 12, 13, 21]]

"""### Why this matters:
In research code, `enumerate()` is often used when you need both subject numbers and filenames, like looping through files `sub1.csv`, `sub2.csv`, etc.

## `F-string`

This is a concise and convenient way to embed Python expressions (i.e. variable values) inside string literals for formatting.

In the previous `enumerate` example, we saw this `print` statement:
```
print("index_from_1 is", i+1, ", and the last name is", name)
```
This `print` statement joins multiple elements, but the spaces are rigid. You can't easily control them. For example, the whitespace between the number **6** and the following **,** cannot be removed. F-strings make this simpler.

An F-string will start with `f`, followed by the string inside quotation marks (either single quote  or double quotes). Python expressions are embedded in the string using curly brackets {or braces, or curly braces}.
"""

# See how simple it is?
for i, name in enumerate(a_pd_series):
  if i in [5, 12, 13, 21]:
    print(f"index_from_1 is {i+1}, and the last name is {name}")

"""## Assignment 3: Task 1

Now let's apply what you've learned to a real task. You'll loop over a list of DataFrames and add subject IDs dynamically.

`dfs` is a `list` of `pandas.DataFrame`. Yes, we saw that a `list` can be looped over.

Here, the code chunk template starts:
```
for i, df in enumerate(dfs):
    df['id'] = ...
```

So now we know that `i` will change from 0 to the number of `pandas.DataFrame` inside the list `dfs`. When `i` is 0, `df` = `dfs[0]`.

With the first line inside the loop, we are tring to create a new column: `id`. I asked the name to be `'sub1'` for `dfs[0]`.
"""

# @title hidden cell (data preparation)

# Data reading prep - run this block!
github_url = 'https://raw.githubusercontent.com/ohspc89/reprorehab2025/students/contents/week3'
suffix = '.csv'
# Do you recognize `.join()` and a list comprehension?
fnames = ['/'.join((github_url, f'sub{str(x+1).zfill(2)}'+suffix)) for x in range(4)]
# Give column names
column_names = ['Measure_A', 'Measure_B']

# Save all dataframes in a list
dfs = []
# Loop over file names
for fname in fnames:
  # `.append()` is a method that attaches an input at the end of a list
  dfs.append(pd.read_csv(fname, header=None, names=column_names))

# Let's first check the work of this loop
for i, df in enumerate(dfs):
  # Only print when i == 0
  if i == 0:
    print(f"i is {i}")
    print('-----------------------')
    print(f"This is df at i={i}")
    print('-----------------------')
    print(df)

print('=======================')
print('This is dfs[0]')
print('-----------------------')
print(dfs[0])

"""When the loop starts, `i` = 0 and `df` points to `dfs[0]`. On the next iteration, `i` = 1 and `df` points to `dfs[1]`, and so on.

Now we need to prepare the `id` column. The dataframe to which `id` column will be created has three columns. Therefore, `id` column should also have three values. This is why the instructions went: "Repeat as many times as you need".

You can think of this simple solution:
```
for i, df in enumerate(dfs):
    df['id'] = 'sub1'
```
This will automatically fill 'sub1' to all rows of the column `id`.

My second request was this: `id` column of the second dataframe (`dfs[1]`) will have `'sub2'` as its value.

 If you assign `'sub1'` to `df['id']`, as `df` will once be `dfs[0]` and `dfs[1]` the next time, and `dfs[2]` after that, all dataframes of `dfs` will have column `id` with repeated values: 'sub1'.
"""

# Shall we?
for i, df in enumerate(dfs):
  df['id'] = 'sub1'
  # skip making the 'time' column for now
  df = df.iloc[:, [2, 0, 1]]
  dfs[i] = df

# After looping is done, let's check the results
for j, df in enumerate(dfs):
  print(f"This is dfs[{j}]")
  print("-----------------------------")
  print(df)
  print("")

"""All subjects ended up with the same ID (`'sub1'`). Let's fix it by embedding the loop index inside the string using an F-string."""

# RUN THE HIDDEN CELL ABOVE FIRST!

for i, df in enumerate(dfs):
  df['id'] = f'sub{i+1}'
  # skip making the 'time' column for now
  df = df.iloc[:, [2, 0, 1]]
  dfs[i] = df

# After looping is done, let's check the results
for j, df in enumerate(dfs):
  print(f"This is dfs[{j}]")
  print("-----------------------------")
  print(df)
  print("")