# -*- coding: utf-8 -*-
"""Missing_values_pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JQXMtaNRwnBHjwbIYkfd3W7twaiBM2Iw

# Week 3 Extra: Handling Missing values

**Learning outcomes**
- Detect missing values
- Drop, fill, or interpolate
"""

import pandas as pd
import numpy as np

"""## Detecting Missing Values

`pandas` has a function: `.isna()`. This function detects *missing* or *null* values within a Series, DataFrame, or other array-like objects.

These are the two common data types detected by `.isna()`:

- `None`: Python's NULL value / type: `NoneType`
- `numpy.nan`: Not a Number / type: `float`
"""

# For example, if you read a csv file with missing values,
# those missing values are read as 'numpy.nan' values.
url = 'https://raw.githubusercontent.com/ohspc89/reprorehab2025/students/contents/week3/missing_value.csv'
example = pd.read_csv(url, header=None, names=['V0', 'V1', 'V2'])
example

# Check that the returned value is np.float64(nan)
# Why np.float64, though? It's because other values are read as `float`.
# In order to make sure that each column has values of the same data type,
# pandas treats missing values as `numpy.nan`.
example.iloc[1, 1]

# Example 1: pandas.DataFrame & np.nan

# Do you see that `True` is displayed at the locations
# where 'NaN' is printed above?
pd.isna(example)

# Example 2 - pandas.Series & None

# Returned series is `pd.Series([False, False, True, False])`
# The function pd.isna() is applied to each element of the series.
pd.isna(pd.Series([0, 1, None, 33]))

# Example 3 - numpy.ndarray & numpy.nan
pd.isna(np.array([[1, 2, 3], [4, 5, np.nan], [6, 7, 8]]))

# Example 4 - list & None

# If you provide a list as an input to `pd.isna()`,
# it will return a numpy.ndarray
pd.isna([3, 2.0, None, 1.7])

# Here we introduce a simple trick to check if there's a NA value.
# Previously, it was explained that True = 1 and False = 0

# So this will return 1 (= 1 + 0)
True + False

# Any non-zero number will tell you the total number of NA values in each column.
# This may be useful if you have MANY rows in your data.
# `.sum()` by default calculates column sums.
example.isna().sum()

example

# `.any()` finds any column with non-zero values
# So `example.isna()` returns a DataFrame with False and True values

#        V0 |    V1 |    V2 |
#   +-------+-------+-------+
# 0 | False | False | False |
#   +-------+-------+-------+
# 1 | False |  True | False |  <- 'True' means NaN is here
#   +-------+-------+-------+
# 2 |  True | False | False |
#   +-------+-------+-------+

# `example.isna().any(axis=1)` will return True if
# a row has any 'True' value.
example.isna().any(axis=1)

# Boolean indexing - return rows with NaN values in them...
example[example.isna().any(axis=1)]

"""## Handling Missing Values

If you perform a numerical operation using columns containing `NaN`, `NaN`s will dominate.
"""

# Renaming columns - this was introduced in week 2!
example.rename(columns={x:y for x, y in zip(example.columns, ['A', 'B', 'C'])}, inplace=True)

# Let's also add some more rows
example = pd.concat((example, pd.DataFrame({'A': [np.nan, 1.9, 1.3],
                                            'B': [np.nan, 0.6, 0.6],
                                            'C': [2.7, np.nan, 2.4]})),
                    ignore_index=True)

example

# Let's suppose you want to make a new column, 'D'
# which contains values of (A+B)/C.
# You can first think of this operation:
example2 = example.copy()
example2['D'] = (example2['A'] + example2['B']) / example2['C']

# Do you see that when there's NaN, an operation's result is also NaN?
example2

"""`.fillna()` assists you in replacing `NaN` with the values you want."""

# Imputing with a constant

# If you provide a single scalar value inside `.fillna()`,
# all NaN values will be replaced with that scalar value.

# See that all previous NaN values of example are now 0.0s.
example.fillna(0)

# Many vectorized math operations in pandas (ex. `.mean()`) have an argument: 'skipna'
# The default of this argument is True.

# For example, let's calculate column means.
# The returned series has values:
#  A 1.5 (= (1.2 + 1.6 + 1.9 + 1.3)/4)       <- NaN skipped
#  B 0.6 (= (0.7 + 0.5 + 0.6 + 0.6)/4)       <- NaN skipped
#  C 2.58 (= (2.3 + 2.6 + 2.9 + 2.7 + 2.4)/5)
example.mean()

# Imputing with mean / median / etc.

# You can directly feed this series to `.fillna()`.
# This fills the NaN value of the column A with the mean of that column (1.5).
# The same will happen to other two columns.
example.fillna(example.mean())

# You can feed a dictionary too.
# The keys of this dictionary should be the same as the columns of the DataFrame
# whose missing values would be filled.

# Here we're replacing NaN values of column A with the column mean,
# NaN values of column B with the column median,
# and NaN values of column C with the column minimum
example.fillna({'A': example['A'].mean(),
                'B':example['B'].median(),
                'C': example['C'].min()})

"""`.dropna()` will drop rows with `NA` values."""

example.dropna()

# You can select which columns would be considered for dropping NA values.
# Please specify the value for the argument: `subset`

# For example, this command will drop rows whose column "A" values are NaN.
# Rows 2, 3 had NaN in Column A. Thus only those two rows are rejected.
example.dropna(subset=["A"])

# Multiple columns can be selected. Do you recognize that the value for
# the argument: `subset` is a list?
example.dropna(subset=["A", "C"])

"""## Interpolating timeseries data"""

# Fake IMU-like time series
rng = pd.date_range('2025-01-01', periods=10, freq='200ms')
# Setting the seed for a random number generator.
np.random.seed(24)
df = pd.DataFrame({'time':rng, 'acc_z': np.random.randn(10)})
df.loc[[3, 7], 'acc_z'] = np.nan  # simulate sample dropout
# See that 'NaN (Not a Number)' is in row '3', column 'acc_z'
df

# `.set_index()` is a method to make a column an index (row labels)
df2 = df.set_index('time')
# Compare the output with the one above - do you see the difference?
df2

# Each index is a Timestamp (introduced in Week 2 extra)
df2.index[0]

# Plotting the data
# Yup, we see there's a missing data point!
# Do you also see that x ticks show date and time?
df2.plot(marker='o')

# We can 'forward fill' (fill NA values using the last non-NA value before the NA value) or
# 'backward fill' (fill NA values using the first non-NA value after the NA value)
df2["ffill"] = df2["acc_z"].fillna(method='ffill')
df2

# Backward fill
df2['bfill'] = df2["acc_z"].fillna(method='bfill')
df2

# Pandas has `.interpolate()` function.
# This does the linear interpolation (default).
# The two adjacent values before and after
# our missing value at 2025-01-01 00:00:00.600 are
# -0.316280 and -1.070816.
# Linear interpolation will get the average of the two:
# {(-0.316280) + (-1.070816)} / 2 = -0.683548
df2["interp_linear"] = df2["acc_z"].interpolate()
df2

# 'ffill' introduced earlier can be done using `.interpolate(method='pad')`
df2["pad"] = df2["acc_z"].interpolate(method='pad')

ax = df2.iloc[2:9, 2].plot(marker='<', linestyle='dashed', label='bfill', c='C1')
df2.iloc[2:9, 1].plot(ax=ax, marker='>', linestyle='dashdot', label='ffill/pad interpolation', c='C2')
df2.iloc[2:9, 3].plot(ax=ax, marker='+', linestyle='dotted', label='linear interpolation', c='C3')
df2["acc_z"].plot(ax=ax, marker='o', linestyle='solid', label='acc_z', c='C0')
ax.legend()

# There are other options available. Provide the value for the argument: `method`
# Possible options would be 'linear' (default), 'polynomial', 'cubic', 'time',
# or 'piecewise_polynomial'. There are more options available.

# 1) polynomial, 2nd order
df2["interp_poly"] = df2["acc_z"].interpolate(method='polynomial', order=2)
# 2) cubic
df2["interp_cubic"] = df2["acc_z"].interpolate(method='cubic')
# 3) time
df2["interp_time"] = df2["acc_z"].interpolate(method='time')

# See how different interpolation methods compare
# As timestamp interval is consistent, 'time' and 'linear' interpolations are the same.
ax = df2.iloc[2:9, 2].plot(marker='<', linestyle='dashed', label='bfill', c='C1')
df2.iloc[2:9, 4].plot(ax=ax, marker='>', linestyle='dashdot', label='ffill/pad interpolation', c='C2')
df2.iloc[2:9, 7].plot(ax=ax, marker='s', linestyle='dashdot', label='time interpolation', c='C4')
df2.iloc[2:9, 3].plot(ax=ax, marker='+', markersize=15, linestyle='dashed', label='linear interpolation', c='C3', alpha=0.8)
df2.iloc[2:9, 5].plot(ax=ax, marker='^', linestyle='dashdot', label='polynomial interpolation', c='C5')
df2.iloc[2:9, 6].plot(ax=ax, marker='v', linestyle='dashed', label='cubic interpolation', c='C6')
df2["acc_z"].plot(ax=ax, marker='o', linestyle='solid', label='acc_z', c='C0')
ax.set_ylim([-1.8, 1.0])
ax.legend()

"""### Final remarks

As I prepared this notebook, I learned of this [page](https://www.kaggle.com/code/parulpandey/a-guide-to-handling-missing-values-in-python). Feel free to check this page out as well!
"""