# -*- coding: utf-8 -*-
"""Week3_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aqh6pPcYRE3rj8TamWBbI_-34Ar4xcFZ

# Week 3 Assignment - Tabular Data Manipulation with pandas

**Objective**:
You'll practice creating, reshaping, and filtering tabular data using core pandas function such as `.concat()`, `.melt()`, and `.pivot()`.

## Setup

For the assignment, you'll use four small synthetic datasets available on GitHub. Each file contains two columns: `Measure_A` and `Measure_B`.

```
--+-----------+-----------+
  | Measure_A | Measure_B |
--+-----------+-----------+
0 |       3.2 |       2.8 |
--+-----------+-----------+
1 |       7.8 |       9.1 |
--+-----------+-----------+
2 |       5.1 |       7.6 |
--+-----------+-----------+
```

The following code downloads them for you:
"""

import pandas as pd

# This is exactly the same as what's included in the notebook.
# Data reading prep - run this block!
github_url = 'https://raw.githubusercontent.com/ohspc89/reprorehab2025/students/contents/week3'
suffix = '.csv'
# Do you recognize `.join()` and a list comprehension?
fnames = ['/'.join((github_url, f'sub{str(x+1).zfill(2)}'+suffix)) for x in range(4)]
# Give column names
column_names = ['Measure_A', 'Measure_B']

# Save all dataframes in a list
dfs = []
# Loop over file names
for fname in fnames:
  # `.append()` is a method that attaches an input at the end of a list
  dfs.append(pd.read_csv(fname, header=None, names=column_names))

"""*Note* 1. `{str}.join(iterable)`

ALWAYS! an 'iterable' is something that you can loop over (ex. tuple, list, dictionary...)

For `.join()`, the elements of this iterable should be all string.

`{str}` is something that will be placed between the elements of an iterable.
"""

# Practice `{str}.join(iterable)`
# ALWAYS! an 'iterable' is something that you can loop over (ex. tuple, list, dictionary...)
# for `.join()`, the elements of this iterable should be all string.
# {str} is something that will be placed between the elements of an iterable.

###########################################
# Run this cell to see what's printed out #
###########################################
# ex1. 'C:/Users/Jinseok/Documents' <- an iterable is a list: ['C:', 'Users', 'Jinseok', 'Documents']
print('/'.join(['C:', 'Users', 'Jinseok', 'Documents']))
print('===========================')
# ex2. 'sub1.csv' <- an iterable is a tuple: ('sub1', 'csv')
print('.'.join(('sub1', 'csv')))
print('===========================')
# ex3. '1 2 3 4' <- an iterable is a range
# ' '.join(range(1,5)) <- this will fail, because you are giving integers, not string elements
# How do you make a number into a string? You can either use `str()` function,
# or you can use f-string
print(' '.join(str(x) for x in range(1, 5)))
print('===========================')
# This is another method
print(' '.join(f'{x}' for x in range(1, 5)))
print('===========================')

"""*Note* 2. `.zfill(n)` and `F string`

Let's read this line:
`fnames = ['/'.join((github_url, f'sub{str(x+1).zfill(2)}'+suffix)) for x in range(4)]`

We are creating a `list` variable, `fnames`.
You can tell by now that it's a `list comprehension` - there's a loop inside this list (`[ ... for x in range(4)]`).


Ok, and the comprehension seems to be joining an iterable using '/' (ex1.)
What's an iterable? It's a `tuple`: `(github_url, f'sub{str(x+1).zfill(2)}'+suffix)`

So we have TWO elements inside this tuple: `github_url` and `f'sub{str(x+1).zfill(2)}'+suffix`

`github_url` we know, because it's defined.

`f'sub{str(x+1).zfill(2)}'+suffix` is a two part thing.

`suffix` is a string variable (= '.csv'). It is added to `f'...{...}'`,
which is also a string (See ex3 above).
It starts with `'sub'` then `{str(x+1).zfill(2)}`. We know that `x` is iterating from 0 to 3 (=`range(4)`).

`.zfill(n)` is a method that zeropads a string with until it reaches the length n.
"""

print('.zfill(2) example I: the string has not yet reached the length 2')
print('3'.zfill(2))
print('===========================')
print('.zfill(2) example II: the string already reached the length 2')
print('39'.zfill(2))

"""So it will be:

- `{str(0+1).zfill(2)}` -> `{str(1).zfill(2)}` -> `'01'`

- `{str(1+1).zfill(2)}` -> `{str(2).zfill(2)}` -> `'02'`

- `{str(2+1).zfill(2)}` -> `{str(3).zfill(2)}` -> `'03'`

- `{str(3+1).zfill(2)}` -> `{str(4).zfill(2)}` -> `'04'`

Putting together, `f'sub{str(x+1).zfill(2)}'+suffix` will make
`'sub01.csv'`, `'sub02.csv'`, `'sub03.csv'`, and `'sub04.csv'`, iteratively.

Finally, `fnames` will be a list of four string elements. The first element will be: 'https://raw.githubusercontent.com/ohspc89/reprorehab2025/students/contents/week3/sub01.csv', which is a csv file sitting in week 3 folder.

*Note* 3. Notice that we store each participant's DataFrame inside a list using `.append()` within a loop. Later we will combine all of them with `pd.concat()`.

## **Task 1**. Add new columns: `id` and `time`

Each DataFrame in `dfs` represents one subject.

- Add an `id` column using `'sub1'`, `'sub2'`, `'sub3'`, `'sub4'` for each subject (*Hint*. Use `F string` with an index, just like what's explained in the notes above).
- Add a `time` column with values `'pre'`, `'test'`, and `'post'`. Convert it into a **categorical variable** using `pd.Categorical()`. Make sure the order of level is: `pre -> test -> post`.

*Note* 4. You can now refer to [this](https://colab.research.google.com/drive/1aJ4U7m_LdWLg_1dvCtQauiKOywgqUeU0?usp=sharing) notebook to see how `enumerate()` works.
"""

# Complete this block
for i, df in enumerate(dfs):
  df['id'] = ...    # if i is 0, this should be repeated accounts of 'sub1'
  df['time'] = ...  # pd.Categorical(...)
  df = df.iloc[:, [2, 3, 0, 1]]
  dfs[i] = df

"""Make sure your `dfs` is properly generated.

*Expected code output* :
```
  +-------+------+-----------+-----------+
  |  id   | time | Measure A | Measure B |
----------+------+-----------+-----------+
0 | sub01 | pre  |       3.2 |       2.8 |
----------+------+-----------+-----------+
1 | sub01 | test |       7.8 |       9.1 |
----------+------+-----------+-----------+
2 | sub01 | post |       5.1 |       7.6 |
----------+------+-----------+-----------+
"""

# You can run this to optionally check your `dfs`
dfs[0]

"""## **Task 2**. Combine all DataFrames

Concatenate all DataFrames in the list (`dfs`) into one large DataFrame using `pd.concat()`.

We will set `ignore_index=True` so that row indices reset automatically.

*Expected code output* :
```
-----+-------+------+-----------+-----------+
     |   id  | time | Measure A | Measure B |
-----+-------+------+-----------+-----------+
 0   | sub01 | pre  |       3.2 |       2.8 |
-----+-------+------+-----------+-----------+
 1   | sub01 | test |       7.8 |       9.1 |
-----+-------+------+-----------+-----------+
 2   | sub01 | post |       5.1 |       7.6 |
-----+-------+------+-----------+-----------+
 ... |  ...  |  ... |       ... |       ... |
-----+-------+------+-----------+-----------+
 9   | sub04 | pre  |       4.4 |       5.5 |
-----+-------+------+-----------+-----------+
 10  | sub04 | test |       8.1 |       7.1 |
-----+-------+------+-----------+-----------+
 11  | sub04 | post |       2.7 |       6.8 |
-----+-------+------+-----------+-----------+
```
"""

# Complete this code block, and check the value of this variable.
with_id = pd.concat(..., ignore_index=True)

"""## **Task 3**. Reshape to Long Format

Use `pd.DataFrame.melt()` to convert your wide DataFrame into *long* format.

You only need to specify:
- `id_vars`: the columns you want to keep fixed (e.g., `['id', 'time']`)
- `value_vars`: the columns you want to "unpivot" (e.g., `['Measure_A', 'Measure_B']`).

Let the other arguments stay at default.

*Expected code output* :
```
  id  | time |  variable | value |
------+------+-----------+-------+
sub01 |  pre | Measure A |   3.2 |
------+------+-----------+-------+
sub01 | test | Measure A |   7.8 |
------+------+-----------+-------+
sub01 | post | Measure A |   5.1 |
------+------+-----------+-------+
 ...  | ...  |    ...    |   ... |
------+------+-----------+-------+
sub04 |  pre | Measure B |   5.5 |
------+------+-----------+-------+
sub04 | test | Measure B |   7.1 |
------+------+-----------+-------+
sub04 | post | Measure B |   6.8 |
------+------+-----------+-------+
"""

# Use `pd.DataFrame.melt()` to prepare a long format
long_form = with_id.melt(id_vars=...,
                         value_vars=...)

"""## **Task 4**. Reshape Back to Wide Format

Now reshape the long-form DataFrame back into a wide form using `pd.DataFrame.pivot()`.

"""

# Use `pandas.DataFrame.pivot()`
wide_form = long_form.pivot(...)

""" After pivoting, use this provided code to make your columns more readable and reset the index."""

# Copying from the learning materials - run it please!
wide_form.columns = ['-'.join((x[1], x[0])) for x in wide_form.columns]
# If you skip this command, 'id' will stay as index.
wide_form = wide_form.reset_index()

"""Run the code block below to prepare `back_to_long`."""

back_to_long = wide_form.melt(id_vars='id')
# Use `.sort_values(by='id')` to sort by the column: id
# Use `.reset_index(drop=True)` to reset the row numbers
back_to_long = back_to_long.sort_values(by='id').reset_index(drop=True)

"""## **Task 5**. Split the "variable" column

Using `back_to_long`, separate the information contained in the `variable` column.

- Use `.str.split('-', expand=True)` to split into two new columns: `variable` and `time`.
- Assign them as new columns within the same DataFrame.
"""

# Complete the code
back_to_long[['variable', 'time']] = ...

"""## **Task 6**. Convert `time` back to categorical

Use `pd.Categorical()` again to ensure `time` follows the correct order: `['pre', 'test', 'post']`.
"""

# Complete the code
back_to_long['time'] = pd.Categorical(...)

"""## **Task 7**. Sort the DataFrame

Sort `back_to_long` so that it looks like this:
```
     id | time | variable  | value |
--------+------+-----------+-------|
0  sub1 | pre  | Meausre_A | 3.2   |
1  sub1 | test | Measure_A | 7.8   |
2  sub1 | post | Measure_A | 5.1   |
3  sub2 | pre  | Measure_A | 9.8   |
4  sub2 | test | Measure_A | 1.2   |
5  sub2 | post | Measure_A | 7.7   |
   ...  | ...  |    ...    | ...   |
21 sub4 | pre  | Measure_B | 5.5   |
22 sub4 | test | Measure_B | 7.1   |
23 sub4 | post | Measure_B | 6.8   |
-----------------------------------+
```

Use `.sort_values(by=['id', 'variable', 'time'])` and then reset the index with `.reset_index(drop=True)`.
"""

# Complete the code
back_to_long.sort_values(by=...).reset_index(drop=True).iloc[:, [0, 3, 1, 2]]

"""## Task 8. Practice filtering (wide format)

**a**. Select columns that end with `"pre"` using `.str.endswith('pre')`.

**b**. Select all `Measure_A` columns for `sub1` using `.str.startswith('Measure_A')`.
"""

# 8a. Only take columns whose names end with 'pre'. Use `.str.endswith()`.

# Expected output:

# Measure_A-pre | Measure_B-pre |
# --------------+---------------|
#           3.2 |           2.8 |
#           9.8 |           3.3 |
#           6.2 |           2.7 |
#           4.4 |           5.5 |
# ------------------------------+
wide_form.loc[...]

# 8b. Check "Measure_A' values of 'sub1' at all time points. Use `.str.startswith()`.

# Expected output:

# Measure_A-pre | Measure_A-test | Measure_A-post |
# --------------+----------------+----------------|
#           3.2 |            7.8 |            5.1 |
wide_form.loc[...]

"""## Task 9. Practice filtering (long format)

**a**. From `back_to_long`, select rows where:

- `time` is `"pre"` and
- `variable` ends with `"B"`.

Use `.loc[]`, `.str.match()`, and `.str.endswith()` together.

**b**. From the same DataFrame, filter rows where `value < 4.0`.
"""

# 9a. Filter out rows whose 'time' is 'pre' and whose 'variable' ends with 'B'.
# Use `.str.match()` and `.str.endswith()`.

# Expected output

#     id | time | variable  | value |
# -------+------+-----------+-------|
#   sub1 | pre  | Meausre_B | 2.8   |
#   sub2 | pre  | Measure_B | 3.3   |
#   sub3 | pre  | Measure_B | 2.7   |
#   sub4 | pre  | Measure_B | 5.5   |
# ----------------------------------+

long_form.loc[...]

# 9b. Take rows whose 'value' is less than 4.0
long_form.loc[...]

"""## Wrap-up

By completing this assignment, you've practiced:

- Creating and combining multiple DataFrames.
- Reshaping data between long and wide formats.
- Using string operations and logical filters.

These are the exact techniques researchers use when preparing experiment data for analysis or visualization.
"""